// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 666498700714

package operations

import (
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
	"github.com/wistia/wistia-cli/internal/sdk/optionalnullable"
	"github.com/wistia/wistia-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type DeleteFoldersIDRequest struct {
	// Folder Hashed ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteFoldersIDRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

// DeleteFoldersIDType - A string representing what type of media this is.
type DeleteFoldersIDType string

const (
	DeleteFoldersIDTypeVideo                   DeleteFoldersIDType = "Video"
	DeleteFoldersIDTypeAudio                   DeleteFoldersIDType = "Audio"
	DeleteFoldersIDTypeImage                   DeleteFoldersIDType = "Image"
	DeleteFoldersIDTypePdfDocument             DeleteFoldersIDType = "PdfDocument"
	DeleteFoldersIDTypeMicrosoftOfficeDocument DeleteFoldersIDType = "MicrosoftOfficeDocument"
	DeleteFoldersIDTypeSwf                     DeleteFoldersIDType = "Swf"
	DeleteFoldersIDTypeUnknownType             DeleteFoldersIDType = "UnknownType"
)

func (e DeleteFoldersIDType) ToPointer() *DeleteFoldersIDType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DeleteFoldersIDType) IsExact() bool {
	if e != nil {
		switch *e {
		case "Video", "Audio", "Image", "PdfDocument", "MicrosoftOfficeDocument", "Swf", "UnknownType":
			return true
		}
	}
	return false
}

// DeleteFoldersIDStatus - Post upload processing status. - `queued`: the file is waiting in the queue to be processed. - `processing`: the file is actively being processed. - `ready`: the file has been fully processed and is ready for embedding and viewing. - `failed`: the file was unable to be processed (usually a format or size error).
type DeleteFoldersIDStatus string

const (
	DeleteFoldersIDStatusQueued     DeleteFoldersIDStatus = "queued"
	DeleteFoldersIDStatusProcessing DeleteFoldersIDStatus = "processing"
	DeleteFoldersIDStatusReady      DeleteFoldersIDStatus = "ready"
	DeleteFoldersIDStatusFailed     DeleteFoldersIDStatus = "failed"
)

func (e DeleteFoldersIDStatus) ToPointer() *DeleteFoldersIDStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DeleteFoldersIDStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "queued", "processing", "ready", "failed":
			return true
		}
	}
	return false
}

type DeleteFoldersIDThumbnail struct {
	URL    *string `json:"url,omitzero"`
	Width  *int64  `json:"width,omitzero"`
	Height *int64  `json:"height,omitzero"`
}

func (d *DeleteFoldersIDThumbnail) GetURL() *string {
	if d == nil {
		return nil
	}
	return d.URL
}

func (d *DeleteFoldersIDThumbnail) GetWidth() *int64 {
	if d == nil {
		return nil
	}
	return d.Width
}

func (d *DeleteFoldersIDThumbnail) GetHeight() *int64 {
	if d == nil {
		return nil
	}
	return d.Height
}

// DeleteFoldersIDMedias - A link to where you can fetch the medias for this folder.
type DeleteFoldersIDMedias struct {
	// A unique numeric identifier for the media within the system.
	ID *int64 `json:"id,omitzero"`
	// The display name of the media.
	Name *string `json:"name,omitzero"`
	// A string representing what type of media this is.
	Type *DeleteFoldersIDType `json:"type,omitzero"`
	// Whether or not the media is archived, either true or false.
	Archived *bool `json:"archived,omitzero"`
	// The date when the media was originally uploaded.
	Created *time.Time `json:"created,omitzero"`
	// The date when the media was last changed.
	Updated *time.Time `json:"updated,omitzero"`
	// Specifies the length (in seconds) for audio and video files. Specifies number of pages in the document. Omitted for other types of media.
	Duration optionalnullable.OptionalNullable[float64] `json:"duration,omitzero"`
	// DEPRECATED: If you want to programmatically embed videos, follow the construct an embed code guide.
	//
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	EmbedCode *string `json:"embedCode,omitzero"`
	// A unique alphanumeric identifier for this media.
	HashedID *string `json:"hashed_id,omitzero"`
	// A description for the media which usually appears near the top of the sidebar on the media's page.
	Description *string `json:"description,omitzero"`
	// A floating point value between 0 and 1 that indicates the progress of the processing for this file.
	Progress *float64 `json:"progress,omitzero"`
	// Post upload processing status. - `queued`: the file is waiting in the queue to be processed. - `processing`: the file is actively being processed. - `ready`: the file has been fully processed and is ready for embedding and viewing. - `failed`: the file was unable to be processed (usually a format or size error).
	//
	Status *DeleteFoldersIDStatus `json:"status,omitzero"`
	// The title of the section in which the media appears. This attribute is omitted if the media is not in a section (default).
	Section   optionalnullable.OptionalNullable[string] `json:"section,omitzero"`
	Thumbnail *DeleteFoldersIDThumbnail                 `json:"thumbnail,omitzero"`
}

func (d DeleteFoldersIDMedias) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteFoldersIDMedias) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteFoldersIDMedias) GetID() *int64 {
	if d == nil {
		return nil
	}
	return d.ID
}

func (d *DeleteFoldersIDMedias) GetName() *string {
	if d == nil {
		return nil
	}
	return d.Name
}

func (d *DeleteFoldersIDMedias) GetType() *DeleteFoldersIDType {
	if d == nil {
		return nil
	}
	return d.Type
}

func (d *DeleteFoldersIDMedias) GetArchived() *bool {
	if d == nil {
		return nil
	}
	return d.Archived
}

func (d *DeleteFoldersIDMedias) GetCreated() *time.Time {
	if d == nil {
		return nil
	}
	return d.Created
}

func (d *DeleteFoldersIDMedias) GetUpdated() *time.Time {
	if d == nil {
		return nil
	}
	return d.Updated
}

func (d *DeleteFoldersIDMedias) GetDuration() optionalnullable.OptionalNullable[float64] {
	if d == nil {
		return nil
	}
	return d.Duration
}

func (d *DeleteFoldersIDMedias) GetEmbedCode() *string {
	if d == nil {
		return nil
	}
	return d.EmbedCode
}

func (d *DeleteFoldersIDMedias) GetHashedID() *string {
	if d == nil {
		return nil
	}
	return d.HashedID
}

func (d *DeleteFoldersIDMedias) GetDescription() *string {
	if d == nil {
		return nil
	}
	return d.Description
}

func (d *DeleteFoldersIDMedias) GetProgress() *float64 {
	if d == nil {
		return nil
	}
	return d.Progress
}

func (d *DeleteFoldersIDMedias) GetStatus() *DeleteFoldersIDStatus {
	if d == nil {
		return nil
	}
	return d.Status
}

func (d *DeleteFoldersIDMedias) GetSection() optionalnullable.OptionalNullable[string] {
	if d == nil {
		return nil
	}
	return d.Section
}

func (d *DeleteFoldersIDMedias) GetThumbnail() *DeleteFoldersIDThumbnail {
	if d == nil {
		return nil
	}
	return d.Thumbnail
}

// DeleteFoldersIDResponseBody - A folder (previously called a project) is a container in which to organize media into. It can be
// used to set permissions that apply to all the media in the folder as well as
// organizing media into subfolders (previously called media groups).
type DeleteFoldersIDResponseBody struct {
	// A unique numeric identifier for the folder within the system.
	ID int64 `json:"id"`
	// The folder’s display name.
	Name string `json:"name"`
	// The folder’s description.
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	// The number of different medias that have been uploaded to the folder.
	MediaCount int64 `json:"media_count"`
	// A link to where you can fetch the medias for this folder.
	Medias DeleteFoldersIDMedias `json:"medias"`
	// The date that the folder was originally created.
	Created time.Time `json:"created"`
	// The date that the folder was last updated.
	Updated time.Time `json:"updated"`
	// A private hashed id, uniquely identifying the folder within the system.
	HashedID string `json:"hashed_id"`
	// A boolean indicating whether the folder is available for public (anonymous) viewing.
	Public bool `json:"public"`
	// If the folder is public, this field contains a string representing the ID used for referencing the folder in public URLs.
	PublicID             *string `json:"public_id"`
	AnonymousCanUpload   *bool   `json:"anonymous_can_upload,omitzero"`
	AnonymousCanDownload *bool   `json:"anonymous_can_download,omitzero"`
	// A cursor for stable pagination based on current `sort_by` order. You can pass this to `cursor[before]` or `cursor[after]` as a parameter to fetch the records before or after this record in the same sort order. This is only populated if records were fetched with `cursor[enabled]`, or `cursor[before]` or `cursor[after]`.
	Cursor optionalnullable.OptionalNullable[string] `json:"cursor,omitzero"`
}

func (d DeleteFoldersIDResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteFoldersIDResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteFoldersIDResponseBody) GetID() int64 {
	if d == nil {
		return 0
	}
	return d.ID
}

func (d *DeleteFoldersIDResponseBody) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

func (d *DeleteFoldersIDResponseBody) GetDescription() optionalnullable.OptionalNullable[string] {
	if d == nil {
		return nil
	}
	return d.Description
}

func (d *DeleteFoldersIDResponseBody) GetMediaCount() int64 {
	if d == nil {
		return 0
	}
	return d.MediaCount
}

func (d *DeleteFoldersIDResponseBody) GetMedias() DeleteFoldersIDMedias {
	if d == nil {
		return DeleteFoldersIDMedias{}
	}
	return d.Medias
}

func (d *DeleteFoldersIDResponseBody) GetCreated() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.Created
}

func (d *DeleteFoldersIDResponseBody) GetUpdated() time.Time {
	if d == nil {
		return time.Time{}
	}
	return d.Updated
}

func (d *DeleteFoldersIDResponseBody) GetHashedID() string {
	if d == nil {
		return ""
	}
	return d.HashedID
}

func (d *DeleteFoldersIDResponseBody) GetPublic() bool {
	if d == nil {
		return false
	}
	return d.Public
}

func (d *DeleteFoldersIDResponseBody) GetPublicID() *string {
	if d == nil {
		return nil
	}
	return d.PublicID
}

func (d *DeleteFoldersIDResponseBody) GetAnonymousCanUpload() *bool {
	if d == nil {
		return nil
	}
	return d.AnonymousCanUpload
}

func (d *DeleteFoldersIDResponseBody) GetAnonymousCanDownload() *bool {
	if d == nil {
		return nil
	}
	return d.AnonymousCanDownload
}

func (d *DeleteFoldersIDResponseBody) GetCursor() optionalnullable.OptionalNullable[string] {
	if d == nil {
		return nil
	}
	return d.Cursor
}

type DeleteFoldersIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	Object *DeleteFoldersIDResponseBody
}

func (d DeleteFoldersIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteFoldersIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteFoldersIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteFoldersIDResponse) GetObject() *DeleteFoldersIDResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}
