// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5c50cebb479a

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
	"github.com/wistia/wistia-cli/internal/sdk/sdkinternal/utils"
	"github.com/wistia/wistia-cli/internal/sdk/types"
)

// GetAnalyticsMediasMediaIDEmbedLocationsSortBy - The metric to sort embed locations by.
type GetAnalyticsMediasMediaIDEmbedLocationsSortBy string

const (
	GetAnalyticsMediasMediaIDEmbedLocationsSortByPlays          GetAnalyticsMediasMediaIDEmbedLocationsSortBy = "plays"
	GetAnalyticsMediasMediaIDEmbedLocationsSortByLoads          GetAnalyticsMediasMediaIDEmbedLocationsSortBy = "loads"
	GetAnalyticsMediasMediaIDEmbedLocationsSortByEngagementRate GetAnalyticsMediasMediaIDEmbedLocationsSortBy = "engagement_rate"
	GetAnalyticsMediasMediaIDEmbedLocationsSortByPlayRate       GetAnalyticsMediasMediaIDEmbedLocationsSortBy = "play_rate"
)

func (e GetAnalyticsMediasMediaIDEmbedLocationsSortBy) ToPointer() *GetAnalyticsMediasMediaIDEmbedLocationsSortBy {
	return &e
}
func (e *GetAnalyticsMediasMediaIDEmbedLocationsSortBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "plays":
		fallthrough
	case "loads":
		fallthrough
	case "engagement_rate":
		fallthrough
	case "play_rate":
		*e = GetAnalyticsMediasMediaIDEmbedLocationsSortBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetAnalyticsMediasMediaIDEmbedLocationsSortBy: %v", v)
	}
}

// GetAnalyticsMediasMediaIDEmbedLocationsSortDirection - The sort direction.
type GetAnalyticsMediasMediaIDEmbedLocationsSortDirection string

const (
	GetAnalyticsMediasMediaIDEmbedLocationsSortDirectionAsc  GetAnalyticsMediasMediaIDEmbedLocationsSortDirection = "asc"
	GetAnalyticsMediasMediaIDEmbedLocationsSortDirectionDesc GetAnalyticsMediasMediaIDEmbedLocationsSortDirection = "desc"
)

func (e GetAnalyticsMediasMediaIDEmbedLocationsSortDirection) ToPointer() *GetAnalyticsMediasMediaIDEmbedLocationsSortDirection {
	return &e
}
func (e *GetAnalyticsMediasMediaIDEmbedLocationsSortDirection) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = GetAnalyticsMediasMediaIDEmbedLocationsSortDirection(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetAnalyticsMediasMediaIDEmbedLocationsSortDirection: %v", v)
	}
}

type GetAnalyticsMediasMediaIDEmbedLocationsRequest struct {
	// The hashed ID of the video.
	MediaID string `pathParam:"style=simple,explode=false,name=mediaId"`
	// Start date for the analytics period in ISO 8601 format (YYYY-MM-DD). Inclusive — the range starts at the beginning of this date.
	StartDate types.Date `queryParam:"style=form,explode=true,name=start_date"`
	// End date for the analytics period in ISO 8601 format (YYYY-MM-DD). Exclusive — the range ends before the beginning of this date.
	EndDate types.Date `queryParam:"style=form,explode=true,name=end_date"`
	// The metric to sort embed locations by.
	SortBy *GetAnalyticsMediasMediaIDEmbedLocationsSortBy `default:"plays" queryParam:"style=form,explode=true,name=sort_by"`
	// The sort direction.
	SortDirection *GetAnalyticsMediasMediaIDEmbedLocationsSortDirection `default:"desc" queryParam:"style=form,explode=true,name=sort_direction"`
	// Filter results to a single embed URL. When provided, only analytics for
	// the page matching this URL are returned. Must be a valid HTTP or HTTPS URL.
	//
	EmbedURL *string `queryParam:"style=form,explode=true,name=embed_url"`
	// Number of results to return (max 100).
	PerPage *int64 `default:"10" queryParam:"style=form,explode=true,name=per_page"`
}

func (g GetAnalyticsMediasMediaIDEmbedLocationsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAnalyticsMediasMediaIDEmbedLocationsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAnalyticsMediasMediaIDEmbedLocationsRequest) GetMediaID() string {
	if g == nil {
		return ""
	}
	return g.MediaID
}

func (g *GetAnalyticsMediasMediaIDEmbedLocationsRequest) GetStartDate() types.Date {
	if g == nil {
		return types.Date{}
	}
	return g.StartDate
}

func (g *GetAnalyticsMediasMediaIDEmbedLocationsRequest) GetEndDate() types.Date {
	if g == nil {
		return types.Date{}
	}
	return g.EndDate
}

func (g *GetAnalyticsMediasMediaIDEmbedLocationsRequest) GetSortBy() *GetAnalyticsMediasMediaIDEmbedLocationsSortBy {
	if g == nil {
		return nil
	}
	return g.SortBy
}

func (g *GetAnalyticsMediasMediaIDEmbedLocationsRequest) GetSortDirection() *GetAnalyticsMediasMediaIDEmbedLocationsSortDirection {
	if g == nil {
		return nil
	}
	return g.SortDirection
}

func (g *GetAnalyticsMediasMediaIDEmbedLocationsRequest) GetEmbedURL() *string {
	if g == nil {
		return nil
	}
	return g.EmbedURL
}

func (g *GetAnalyticsMediasMediaIDEmbedLocationsRequest) GetPerPage() *int64 {
	if g == nil {
		return nil
	}
	return g.PerPage
}

// GetAnalyticsMediasMediaIDEmbedLocationsCode - A machine-readable identifier for the specific authorization failure.
type GetAnalyticsMediasMediaIDEmbedLocationsCode string

const (
	GetAnalyticsMediasMediaIDEmbedLocationsCodeUnauthorizedCredentials GetAnalyticsMediasMediaIDEmbedLocationsCode = "unauthorized_credentials"
	GetAnalyticsMediasMediaIDEmbedLocationsCodeAccountInactive         GetAnalyticsMediasMediaIDEmbedLocationsCode = "account_inactive"
	GetAnalyticsMediasMediaIDEmbedLocationsCodeUnauthorizedScope       GetAnalyticsMediasMediaIDEmbedLocationsCode = "unauthorized_scope"
	GetAnalyticsMediasMediaIDEmbedLocationsCodeUnauthorizedParams      GetAnalyticsMediasMediaIDEmbedLocationsCode = "unauthorized_params"
)

func (e GetAnalyticsMediasMediaIDEmbedLocationsCode) ToPointer() *GetAnalyticsMediasMediaIDEmbedLocationsCode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *GetAnalyticsMediasMediaIDEmbedLocationsCode) IsExact() bool {
	if e != nil {
		switch *e {
		case "unauthorized_credentials", "account_inactive", "unauthorized_scope", "unauthorized_params":
			return true
		}
	}
	return false
}

type GetAnalyticsMediasMediaIDEmbedLocationsResponseBody struct {
	// The domain where the video is embedded.
	EmbedDomain *string `json:"embed_domain,omitzero"`
	// The path on the domain where the video is embedded.
	EmbedPath *string `json:"embed_path,omitzero"`
	// The full URL where the video is embedded.
	EmbedURL *string `json:"embed_url,omitzero"`
	// The title of the page where the video is embedded.
	PageTitle *string `json:"page_title,omitzero"`
	// The number of video loads from this location.
	Loads *int64 `json:"loads,omitzero"`
	// The number of unique video loads from this location (one per visitor session).
	UniqueLoads *int64 `json:"unique_loads,omitzero"`
	// The number of video plays from this location.
	Plays *int64 `json:"plays,omitzero"`
	// The number of unique video plays from this location (one per visitor session).
	UniquePlays *int64 `json:"unique_plays,omitzero"`
	// The play rate from this location (between 0 and 1).
	PlayRate *float32 `json:"play_rate,omitzero"`
	// Total time spent watching from this location in seconds.
	PlayedTime *float32 `json:"played_time,omitzero"`
	// The average engagement rate from this location (between 0 and 1).
	EngagementRate *float32 `json:"engagement_rate,omitzero"`
	// The number of unique visitors from this location.
	UniqueVisitors *int64 `json:"unique_visitors,omitzero"`
	// The CTA conversion rate from this location (between 0 and 1).
	CtaConversionRate *float32 `json:"cta_conversion_rate,omitzero"`
}

func (g *GetAnalyticsMediasMediaIDEmbedLocationsResponseBody) GetEmbedDomain() *string {
	if g == nil {
		return nil
	}
	return g.EmbedDomain
}

func (g *GetAnalyticsMediasMediaIDEmbedLocationsResponseBody) GetEmbedPath() *string {
	if g == nil {
		return nil
	}
	return g.EmbedPath
}

func (g *GetAnalyticsMediasMediaIDEmbedLocationsResponseBody) GetEmbedURL() *string {
	if g == nil {
		return nil
	}
	return g.EmbedURL
}

func (g *GetAnalyticsMediasMediaIDEmbedLocationsResponseBody) GetPageTitle() *string {
	if g == nil {
		return nil
	}
	return g.PageTitle
}

func (g *GetAnalyticsMediasMediaIDEmbedLocationsResponseBody) GetLoads() *int64 {
	if g == nil {
		return nil
	}
	return g.Loads
}

func (g *GetAnalyticsMediasMediaIDEmbedLocationsResponseBody) GetUniqueLoads() *int64 {
	if g == nil {
		return nil
	}
	return g.UniqueLoads
}

func (g *GetAnalyticsMediasMediaIDEmbedLocationsResponseBody) GetPlays() *int64 {
	if g == nil {
		return nil
	}
	return g.Plays
}

func (g *GetAnalyticsMediasMediaIDEmbedLocationsResponseBody) GetUniquePlays() *int64 {
	if g == nil {
		return nil
	}
	return g.UniquePlays
}

func (g *GetAnalyticsMediasMediaIDEmbedLocationsResponseBody) GetPlayRate() *float32 {
	if g == nil {
		return nil
	}
	return g.PlayRate
}

func (g *GetAnalyticsMediasMediaIDEmbedLocationsResponseBody) GetPlayedTime() *float32 {
	if g == nil {
		return nil
	}
	return g.PlayedTime
}

func (g *GetAnalyticsMediasMediaIDEmbedLocationsResponseBody) GetEngagementRate() *float32 {
	if g == nil {
		return nil
	}
	return g.EngagementRate
}

func (g *GetAnalyticsMediasMediaIDEmbedLocationsResponseBody) GetUniqueVisitors() *int64 {
	if g == nil {
		return nil
	}
	return g.UniqueVisitors
}

func (g *GetAnalyticsMediasMediaIDEmbedLocationsResponseBody) GetCtaConversionRate() *float32 {
	if g == nil {
		return nil
	}
	return g.CtaConversionRate
}

type GetAnalyticsMediasMediaIDEmbedLocationsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success response with embed location analytics.
	ResponseBodies []GetAnalyticsMediasMediaIDEmbedLocationsResponseBody
}

func (g GetAnalyticsMediasMediaIDEmbedLocationsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAnalyticsMediasMediaIDEmbedLocationsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAnalyticsMediasMediaIDEmbedLocationsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAnalyticsMediasMediaIDEmbedLocationsResponse) GetResponseBodies() []GetAnalyticsMediasMediaIDEmbedLocationsResponseBody {
	if g == nil {
		return nil
	}
	return g.ResponseBodies
}
