// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: bf3fecfdf873

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
	"github.com/wistia/wistia-cli/internal/sdk/sdkinternal/utils"
	"github.com/wistia/wistia-cli/internal/sdk/types"
)

// PathMatch - How to match the path of `embed_url` against embed locations. `exact` requires the path to match exactly; `prefix` matches any embed path starting with it.
type PathMatch string

const (
	PathMatchExact  PathMatch = "exact"
	PathMatchPrefix PathMatch = "prefix"
)

func (e PathMatch) ToPointer() *PathMatch {
	return &e
}
func (e *PathMatch) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "exact":
		fallthrough
	case "prefix":
		*e = PathMatch(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PathMatch: %v", v)
	}
}

type GetAnalyticsAccountMediaByEmbedLocationRequest struct {
	// The URL of the page to look up, e.g. `https://example.com/pricing`. The protocol is optional (https is assumed), so `example.com/pricing` also works.
	EmbedURL string `queryParam:"style=form,explode=true,name=embed_url"`
	// Start date for the analytics period in ISO 8601 format (YYYY-MM-DD). Inclusive — the range starts at the beginning of this date. Must be within the last 6 months. Defaults to 6 months ago, the start of the queryable window.
	StartDate *types.Date `queryParam:"style=form,explode=true,name=start_date"`
	// End date for the analytics period in ISO 8601 format (YYYY-MM-DD). Exclusive — the range ends before the beginning of this date. Defaults to tomorrow, so today's activity is included.
	EndDate *types.Date `queryParam:"style=form,explode=true,name=end_date"`
	// How to match the path of `embed_url` against embed locations. `exact` requires the path to match exactly; `prefix` matches any embed path starting with it.
	PathMatch *PathMatch `default:"exact" queryParam:"style=form,explode=true,name=path_match"`
	// Number of media hashed IDs to return (max 1000).
	PerPage *int64 `default:"100" queryParam:"style=form,explode=true,name=per_page"`
}

func (g GetAnalyticsAccountMediaByEmbedLocationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAnalyticsAccountMediaByEmbedLocationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAnalyticsAccountMediaByEmbedLocationRequest) GetEmbedURL() string {
	if g == nil {
		return ""
	}
	return g.EmbedURL
}

func (g *GetAnalyticsAccountMediaByEmbedLocationRequest) GetStartDate() *types.Date {
	if g == nil {
		return nil
	}
	return g.StartDate
}

func (g *GetAnalyticsAccountMediaByEmbedLocationRequest) GetEndDate() *types.Date {
	if g == nil {
		return nil
	}
	return g.EndDate
}

func (g *GetAnalyticsAccountMediaByEmbedLocationRequest) GetPathMatch() *PathMatch {
	if g == nil {
		return nil
	}
	return g.PathMatch
}

func (g *GetAnalyticsAccountMediaByEmbedLocationRequest) GetPerPage() *int64 {
	if g == nil {
		return nil
	}
	return g.PerPage
}

// GetAnalyticsAccountMediaByEmbedLocationCode - A machine-readable identifier for the specific authorization failure.
type GetAnalyticsAccountMediaByEmbedLocationCode string

const (
	GetAnalyticsAccountMediaByEmbedLocationCodeUnauthorizedCredentials GetAnalyticsAccountMediaByEmbedLocationCode = "unauthorized_credentials"
	GetAnalyticsAccountMediaByEmbedLocationCodeAccountInactive         GetAnalyticsAccountMediaByEmbedLocationCode = "account_inactive"
	GetAnalyticsAccountMediaByEmbedLocationCodeUnauthorizedScope       GetAnalyticsAccountMediaByEmbedLocationCode = "unauthorized_scope"
	GetAnalyticsAccountMediaByEmbedLocationCodeUnauthorizedParams      GetAnalyticsAccountMediaByEmbedLocationCode = "unauthorized_params"
)

func (e GetAnalyticsAccountMediaByEmbedLocationCode) ToPointer() *GetAnalyticsAccountMediaByEmbedLocationCode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *GetAnalyticsAccountMediaByEmbedLocationCode) IsExact() bool {
	if e != nil {
		switch *e {
		case "unauthorized_credentials", "account_inactive", "unauthorized_scope", "unauthorized_params":
			return true
		}
	}
	return false
}

// GetAnalyticsAccountMediaByEmbedLocationResponseBody - Success response with the hashed IDs of media embedded at the location.
type GetAnalyticsAccountMediaByEmbedLocationResponseBody struct {
	// Hashed IDs of media embedded at the location, ranked by plays.
	MediaHashedIds []string `json:"media_hashed_ids,omitzero"`
}

func (g GetAnalyticsAccountMediaByEmbedLocationResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAnalyticsAccountMediaByEmbedLocationResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAnalyticsAccountMediaByEmbedLocationResponseBody) GetMediaHashedIds() []string {
	if g == nil {
		return nil
	}
	return g.MediaHashedIds
}

type GetAnalyticsAccountMediaByEmbedLocationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success response with the hashed IDs of media embedded at the location.
	Object *GetAnalyticsAccountMediaByEmbedLocationResponseBody
}

func (g GetAnalyticsAccountMediaByEmbedLocationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAnalyticsAccountMediaByEmbedLocationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAnalyticsAccountMediaByEmbedLocationResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAnalyticsAccountMediaByEmbedLocationResponse) GetObject() *GetAnalyticsAccountMediaByEmbedLocationResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
