// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 72c11ac4fe79

package operations

import (
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
	"github.com/wistia/wistia-cli/internal/sdk/sdkinternal/utils"
	"time"
)

// GetCreditBalanceCode - A machine-readable identifier for the specific authorization failure.
type GetCreditBalanceCode string

const (
	GetCreditBalanceCodeUnauthorizedCredentials GetCreditBalanceCode = "unauthorized_credentials"
	GetCreditBalanceCodeAccountInactive         GetCreditBalanceCode = "account_inactive"
	GetCreditBalanceCodeUnauthorizedScope       GetCreditBalanceCode = "unauthorized_scope"
	GetCreditBalanceCodeUnauthorizedParams      GetCreditBalanceCode = "unauthorized_params"
)

func (e GetCreditBalanceCode) ToPointer() *GetCreditBalanceCode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *GetCreditBalanceCode) IsExact() bool {
	if e != nil {
		switch *e {
		case "unauthorized_credentials", "account_inactive", "unauthorized_scope", "unauthorized_params":
			return true
		}
	}
	return false
}

// GetCreditBalanceResponseBody - The current account's available Credits balance and expected next recurring grant date.
type GetCreditBalanceResponseBody struct {
	// Available Credits as an exact, nonnegative decimal string.
	Balance string `json:"balance"`
	// Expected next recurring Credits grant boundary from the account's billing schedule, as an ISO 8601 timestamp. Null when no scheduled grant can be determined. Processing may occur later, and other grants may arrive sooner.
	NextGrantAt *time.Time `json:"next_grant_at"`
}

func (g GetCreditBalanceResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCreditBalanceResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetCreditBalanceResponseBody) GetBalance() string {
	if g == nil {
		return ""
	}
	return g.Balance
}

func (g *GetCreditBalanceResponseBody) GetNextGrantAt() *time.Time {
	if g == nil {
		return nil
	}
	return g.NextGrantAt
}

type GetCreditBalanceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	Object *GetCreditBalanceResponseBody
}

func (g GetCreditBalanceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCreditBalanceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetCreditBalanceResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetCreditBalanceResponse) GetObject() *GetCreditBalanceResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
