// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6859bf8306c7

package operations

import (
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
	"github.com/wistia/wistia-cli/internal/sdk/optionalnullable"
	"github.com/wistia/wistia-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type GetMediaExtendedAudioDescriptionsOrderStatusIDRequest struct {
	// The hashed ID of the order returned from the order endpoint.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetMediaExtendedAudioDescriptionsOrderStatusIDRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

// GetMediaExtendedAudioDescriptionsOrderStatusIDOrderStatus - The current status of the order.
type GetMediaExtendedAudioDescriptionsOrderStatusIDOrderStatus string

const (
	GetMediaExtendedAudioDescriptionsOrderStatusIDOrderStatusInProgress GetMediaExtendedAudioDescriptionsOrderStatusIDOrderStatus = "in_progress"
	GetMediaExtendedAudioDescriptionsOrderStatusIDOrderStatusCompleted  GetMediaExtendedAudioDescriptionsOrderStatusIDOrderStatus = "completed"
	GetMediaExtendedAudioDescriptionsOrderStatusIDOrderStatusCancelled  GetMediaExtendedAudioDescriptionsOrderStatusIDOrderStatus = "cancelled"
	GetMediaExtendedAudioDescriptionsOrderStatusIDOrderStatusFailed     GetMediaExtendedAudioDescriptionsOrderStatusIDOrderStatus = "failed"
)

func (e GetMediaExtendedAudioDescriptionsOrderStatusIDOrderStatus) ToPointer() *GetMediaExtendedAudioDescriptionsOrderStatusIDOrderStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *GetMediaExtendedAudioDescriptionsOrderStatusIDOrderStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "in_progress", "completed", "cancelled", "failed":
			return true
		}
	}
	return false
}

type GetMediaExtendedAudioDescriptionsOrderStatusIDMedia struct {
	// A unique alphanumeric identifier for the record.
	ID string `json:"id"`
	// A URL for fetching all the records of the given record type. You can pass hashed_ids as a param with multiple values
	// to do a batch fetch for this records type.
	//
	IndexURL string `json:"index_url"`
	// A URL that can be used to fetch this record.
	URL string `json:"url"`
}

func (g *GetMediaExtendedAudioDescriptionsOrderStatusIDMedia) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetMediaExtendedAudioDescriptionsOrderStatusIDMedia) GetIndexURL() string {
	if g == nil {
		return ""
	}
	return g.IndexURL
}

func (g *GetMediaExtendedAudioDescriptionsOrderStatusIDMedia) GetURL() string {
	if g == nil {
		return ""
	}
	return g.URL
}

type GetMediaExtendedAudioDescriptionsOrderStatusIDMediaExtendedAudioDescription struct {
	// A unique alphanumeric identifier for the record.
	ID string `json:"id"`
	// A URL for fetching all the records of the given record type. You can pass hashed_ids as a param with multiple values
	// to do a batch fetch for this records type.
	//
	IndexURL string `json:"index_url"`
	// A URL that can be used to fetch this record.
	URL string `json:"url"`
}

func (g *GetMediaExtendedAudioDescriptionsOrderStatusIDMediaExtendedAudioDescription) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetMediaExtendedAudioDescriptionsOrderStatusIDMediaExtendedAudioDescription) GetIndexURL() string {
	if g == nil {
		return ""
	}
	return g.IndexURL
}

func (g *GetMediaExtendedAudioDescriptionsOrderStatusIDMediaExtendedAudioDescription) GetURL() string {
	if g == nil {
		return ""
	}
	return g.URL
}

type GetMediaExtendedAudioDescriptionsOrderStatusIDOrder struct {
	// The hashed ID of the order. Use this to poll order status via the order_status endpoint.
	ID string `json:"id"`
	// The current status of the order.
	OrderStatus GetMediaExtendedAudioDescriptionsOrderStatusIDOrderStatus `json:"order_status"`
	CreatedAt   time.Time                                                 `json:"created_at"`
	UpdatedAt   time.Time                                                 `json:"updated_at"`
	Media       GetMediaExtendedAudioDescriptionsOrderStatusIDMedia       `json:"media"`
	// Link to the resulting media extended audio description. Null while the order is in progress.
	MediaExtendedAudioDescription optionalnullable.OptionalNullable[GetMediaExtendedAudioDescriptionsOrderStatusIDMediaExtendedAudioDescription] `json:"media_extended_audio_description,omitzero"`
}

func (g GetMediaExtendedAudioDescriptionsOrderStatusIDOrder) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMediaExtendedAudioDescriptionsOrderStatusIDOrder) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMediaExtendedAudioDescriptionsOrderStatusIDOrder) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetMediaExtendedAudioDescriptionsOrderStatusIDOrder) GetOrderStatus() GetMediaExtendedAudioDescriptionsOrderStatusIDOrderStatus {
	if g == nil {
		return GetMediaExtendedAudioDescriptionsOrderStatusIDOrderStatus("")
	}
	return g.OrderStatus
}

func (g *GetMediaExtendedAudioDescriptionsOrderStatusIDOrder) GetCreatedAt() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.CreatedAt
}

func (g *GetMediaExtendedAudioDescriptionsOrderStatusIDOrder) GetUpdatedAt() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.UpdatedAt
}

func (g *GetMediaExtendedAudioDescriptionsOrderStatusIDOrder) GetMedia() GetMediaExtendedAudioDescriptionsOrderStatusIDMedia {
	if g == nil {
		return GetMediaExtendedAudioDescriptionsOrderStatusIDMedia{}
	}
	return g.Media
}

func (g *GetMediaExtendedAudioDescriptionsOrderStatusIDOrder) GetMediaExtendedAudioDescription() optionalnullable.OptionalNullable[GetMediaExtendedAudioDescriptionsOrderStatusIDMediaExtendedAudioDescription] {
	if g == nil {
		return nil
	}
	return g.MediaExtendedAudioDescription
}

// GetMediaExtendedAudioDescriptionsOrderStatusIDResponseBody - Order status retrieved successfully.
type GetMediaExtendedAudioDescriptionsOrderStatusIDResponseBody struct {
	Order GetMediaExtendedAudioDescriptionsOrderStatusIDOrder `json:"order"`
}

func (g *GetMediaExtendedAudioDescriptionsOrderStatusIDResponseBody) GetOrder() GetMediaExtendedAudioDescriptionsOrderStatusIDOrder {
	if g == nil {
		return GetMediaExtendedAudioDescriptionsOrderStatusIDOrder{}
	}
	return g.Order
}

type GetMediaExtendedAudioDescriptionsOrderStatusIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Order status retrieved successfully.
	Object *GetMediaExtendedAudioDescriptionsOrderStatusIDResponseBody
}

func (g GetMediaExtendedAudioDescriptionsOrderStatusIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMediaExtendedAudioDescriptionsOrderStatusIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMediaExtendedAudioDescriptionsOrderStatusIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetMediaExtendedAudioDescriptionsOrderStatusIDResponse) GetObject() *GetMediaExtendedAudioDescriptionsOrderStatusIDResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
