// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1939b7e7f4e2

package operations

import (
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
	"github.com/wistia/wistia-cli/internal/sdk/sdkinternal/utils"
)

type GetMediasMediaHashedIDCaptionsLanguageCodeRequest struct {
	// The hashed ID of the media from which captions are to be retrieved.
	MediaHashedID string `pathParam:"style=simple,explode=false,name=mediaHashedId"`
	// The language code of the captions to be retrieved.
	LanguageCode string `pathParam:"style=simple,explode=false,name=languageCode"`
}

func (g *GetMediasMediaHashedIDCaptionsLanguageCodeRequest) GetMediaHashedID() string {
	if g == nil {
		return ""
	}
	return g.MediaHashedID
}

func (g *GetMediasMediaHashedIDCaptionsLanguageCodeRequest) GetLanguageCode() string {
	if g == nil {
		return ""
	}
	return g.LanguageCode
}

// GetMediasMediaHashedIDCaptionsLanguageCodeResponseBody - Successful response containing captions in the requested format
type GetMediasMediaHashedIDCaptionsLanguageCodeResponseBody struct {
	// English name of the language.
	EnglishName *string `json:"english_name,omitzero"`
	// Native name of the language.
	NativeName *string `json:"native_name,omitzero"`
	// A 3 character language code as specified by ISO-639–2.
	Language string `json:"language"`
	// The text of the captions for the specified language in SRT format.
	Text    *string `json:"text,omitzero"`
	IsDraft bool    `json:"is_draft"`
	// The unique hashed identifier of the time-coded transcript.
	ID string `json:"id"`
}

func (g *GetMediasMediaHashedIDCaptionsLanguageCodeResponseBody) GetEnglishName() *string {
	if g == nil {
		return nil
	}
	return g.EnglishName
}

func (g *GetMediasMediaHashedIDCaptionsLanguageCodeResponseBody) GetNativeName() *string {
	if g == nil {
		return nil
	}
	return g.NativeName
}

func (g *GetMediasMediaHashedIDCaptionsLanguageCodeResponseBody) GetLanguage() string {
	if g == nil {
		return ""
	}
	return g.Language
}

func (g *GetMediasMediaHashedIDCaptionsLanguageCodeResponseBody) GetText() *string {
	if g == nil {
		return nil
	}
	return g.Text
}

func (g *GetMediasMediaHashedIDCaptionsLanguageCodeResponseBody) GetIsDraft() bool {
	if g == nil {
		return false
	}
	return g.IsDraft
}

func (g *GetMediasMediaHashedIDCaptionsLanguageCodeResponseBody) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetMediasMediaHashedIDCaptionsLanguageCodeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response containing captions in the requested format
	TwoHundredApplicationJSONObject *GetMediasMediaHashedIDCaptionsLanguageCodeResponseBody
	// Successful response containing captions in the requested format
	TwoHundredTextPlainRes *string
	// Successful response containing captions in the requested format
	TwoHundredTextVttRes *string
}

func (g GetMediasMediaHashedIDCaptionsLanguageCodeResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMediasMediaHashedIDCaptionsLanguageCodeResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMediasMediaHashedIDCaptionsLanguageCodeResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetMediasMediaHashedIDCaptionsLanguageCodeResponse) GetTwoHundredApplicationJSONObject() *GetMediasMediaHashedIDCaptionsLanguageCodeResponseBody {
	if g == nil {
		return nil
	}
	return g.TwoHundredApplicationJSONObject
}

func (g *GetMediasMediaHashedIDCaptionsLanguageCodeResponse) GetTwoHundredTextPlainRes() *string {
	if g == nil {
		return nil
	}
	return g.TwoHundredTextPlainRes
}

func (g *GetMediasMediaHashedIDCaptionsLanguageCodeResponse) GetTwoHundredTextVttRes() *string {
	if g == nil {
		return nil
	}
	return g.TwoHundredTextVttRes
}
