// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 91737d613f48

package operations

import (
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
	"github.com/wistia/wistia-cli/internal/sdk/sdkinternal/utils"
)

type GetMediasMediaHashedIDStatsRequest struct {
	// The hashed ID of the video.
	MediaHashedID string `pathParam:"style=simple,explode=false,name=mediaHashedId"`
}

func (g *GetMediasMediaHashedIDStatsRequest) GetMediaHashedID() string {
	if g == nil {
		return ""
	}
	return g.MediaHashedID
}

// Stats - An object representing the aggregated embed statistics for this video.
type Stats struct {
	// The total number of times that the page containing the embedded video has been loaded.
	PageLoads *int64 `json:"pageLoads,omitzero"`
	// The number of unique visitors to the page containing the embedded video.
	Visitors *int64 `json:"visitors,omitzero"`
	// An integer between 0 and 100 that shows what percentage of the time someone who saw the page containing the embedded video played the video.
	PercentOfVisitorsClickingPlay *int64 `json:"percentOfVisitorsClickingPlay,omitzero"`
	// The total number of times that the video has been played.
	Plays *int64 `json:"plays,omitzero"`
	// An integer between 0 and 100. It shows the average percentage of the video that was watched over every time the video was played.
	AveragePercentWatched *int64 `json:"averagePercentWatched,omitzero"`
}

func (s *Stats) GetPageLoads() *int64 {
	if s == nil {
		return nil
	}
	return s.PageLoads
}

func (s *Stats) GetVisitors() *int64 {
	if s == nil {
		return nil
	}
	return s.Visitors
}

func (s *Stats) GetPercentOfVisitorsClickingPlay() *int64 {
	if s == nil {
		return nil
	}
	return s.PercentOfVisitorsClickingPlay
}

func (s *Stats) GetPlays() *int64 {
	if s == nil {
		return nil
	}
	return s.Plays
}

func (s *Stats) GetAveragePercentWatched() *int64 {
	if s == nil {
		return nil
	}
	return s.AveragePercentWatched
}

// GetMediasMediaHashedIDStatsResponseBody - Successful retrieval of video statistics.
type GetMediasMediaHashedIDStatsResponseBody struct {
	// A unique numeric identifier for the video within the system.
	ID *int64 `json:"id,omitzero"`
	// A unique alphanumeric identifier for the video within the system.
	HashedID *string `json:"hashed_id,omitzero"`
	// The display name of the video.
	Name *string `json:"name,omitzero"`
	// An object representing the aggregated embed statistics for this video.
	Stats *Stats `json:"stats,omitzero"`
}

func (g GetMediasMediaHashedIDStatsResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMediasMediaHashedIDStatsResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMediasMediaHashedIDStatsResponseBody) GetID() *int64 {
	if g == nil {
		return nil
	}
	return g.ID
}

func (g *GetMediasMediaHashedIDStatsResponseBody) GetHashedID() *string {
	if g == nil {
		return nil
	}
	return g.HashedID
}

func (g *GetMediasMediaHashedIDStatsResponseBody) GetName() *string {
	if g == nil {
		return nil
	}
	return g.Name
}

func (g *GetMediasMediaHashedIDStatsResponseBody) GetStats() *Stats {
	if g == nil {
		return nil
	}
	return g.Stats
}

type GetMediasMediaHashedIDStatsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful retrieval of video statistics.
	Object *GetMediasMediaHashedIDStatsResponseBody
}

func (g GetMediasMediaHashedIDStatsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMediasMediaHashedIDStatsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMediasMediaHashedIDStatsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetMediasMediaHashedIDStatsResponse) GetObject() *GetMediasMediaHashedIDStatsResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
