// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 69c49668fa9a

package operations

import (
	"encoding/json"
	"errors"
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
	"github.com/wistia/wistia-cli/internal/sdk/sdkinternal/utils"
)

type GetMediasMediaIDCustomizationsThumbnailRequest struct {
	// The hashed ID of the video.
	MediaID string `pathParam:"style=simple,explode=false,name=mediaId"`
}

func (g *GetMediasMediaIDCustomizationsThumbnailRequest) GetMediaID() string {
	if g == nil {
		return ""
	}
	return g.MediaID
}

// GetMediasMediaIDCustomizationsThumbnailCode - A machine-readable identifier for the specific authorization failure.
type GetMediasMediaIDCustomizationsThumbnailCode string

const (
	GetMediasMediaIDCustomizationsThumbnailCodeUnauthorizedCredentials GetMediasMediaIDCustomizationsThumbnailCode = "unauthorized_credentials"
	GetMediasMediaIDCustomizationsThumbnailCodeAccountInactive         GetMediasMediaIDCustomizationsThumbnailCode = "account_inactive"
	GetMediasMediaIDCustomizationsThumbnailCodeUnauthorizedScope       GetMediasMediaIDCustomizationsThumbnailCode = "unauthorized_scope"
	GetMediasMediaIDCustomizationsThumbnailCodeUnauthorizedParams      GetMediasMediaIDCustomizationsThumbnailCode = "unauthorized_params"
)

func (e GetMediasMediaIDCustomizationsThumbnailCode) ToPointer() *GetMediasMediaIDCustomizationsThumbnailCode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *GetMediasMediaIDCustomizationsThumbnailCode) IsExact() bool {
	if e != nil {
		switch *e {
		case "unauthorized_credentials", "account_inactive", "unauthorized_scope", "unauthorized_params":
			return true
		}
	}
	return false
}

type GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAsset struct {
}

func (g GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAsset) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAsset) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

type GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnionType string

const (
	GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnionTypeStr                                                             GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnionType = "str"
	GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnionTypeGetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAsset GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnionType = "get_medias_mediaId_customizations_thumbnail_unalteredStillImageAsset"
	GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnionTypeUnknown                                                         GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnionType = "Unknown"
)

type GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnion struct {
	Str                                                             *string                                                          `queryParam:"inline" union:"member"`
	GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAsset *GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAsset `queryParam:"inline" union:"member"`
	UnknownRaw                                                      json.RawMessage                                                  `json:"-" union:"unknown"`

	Type GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnionType
}

func CreateGetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnionStr(str string) GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnion {
	typ := GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnionTypeStr

	return GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnion{
		Str:  &str,
		Type: typ,
	}
}

func CreateGetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnionGetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAsset(getMediasMediaIDCustomizationsThumbnailUnalteredStillImageAsset GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAsset) GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnion {
	typ := GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnionTypeGetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAsset

	return GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnion{
		GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAsset: &getMediasMediaIDCustomizationsThumbnailUnalteredStillImageAsset,
		Type: typ,
	}
}

func CreateGetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnionUnknown(raw json.RawMessage) GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnion {
	return GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnion{
		UnknownRaw: raw,
		Type:       GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnionTypeUnknown,
	}
}

func (u GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnion) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnion) IsUnknown() bool {
	return u.Type == GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnionTypeUnknown
}

func (u *GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnion) UnmarshalJSON(data []byte) error {
	*u = GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnion{}

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnionTypeStr,
			Value: &str,
		})
	}

	var getMediasMediaIDCustomizationsThumbnailUnalteredStillImageAsset GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAsset = GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAsset{}
	if err := utils.UnmarshalJSON(data, &getMediasMediaIDCustomizationsThumbnailUnalteredStillImageAsset, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnionTypeGetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAsset,
			Value: &getMediasMediaIDCustomizationsThumbnailUnalteredStillImageAsset,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnionTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnionTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnionType)
	switch best.Type {
	case GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnionTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnionTypeGetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAsset:
		u.GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAsset = best.Value.(*GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAsset)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnionTypeUnknown
	return nil
}

func (u GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnion) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAsset != nil {
		return utils.MarshalJSON(u.GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAsset, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnion: all fields are null")
}

type GetMediasMediaIDCustomizationsThumbnailVideoThumbnail struct {
	ClickToPlayButton *string `json:"clickToPlayButton,omitzero"`
	ClickForSound     *string `json:"clickForSound,omitzero"`
	HashedID          *string `json:"hashedId,omitzero"`
	TrimStart         *string `json:"trimStart,omitzero"`
	TrimEnd           *string `json:"trimEnd,omitzero"`
	PriorityMode      *string `json:"priorityMode,omitzero"`
}

func (g *GetMediasMediaIDCustomizationsThumbnailVideoThumbnail) GetClickToPlayButton() *string {
	if g == nil {
		return nil
	}
	return g.ClickToPlayButton
}

func (g *GetMediasMediaIDCustomizationsThumbnailVideoThumbnail) GetClickForSound() *string {
	if g == nil {
		return nil
	}
	return g.ClickForSound
}

func (g *GetMediasMediaIDCustomizationsThumbnailVideoThumbnail) GetHashedID() *string {
	if g == nil {
		return nil
	}
	return g.HashedID
}

func (g *GetMediasMediaIDCustomizationsThumbnailVideoThumbnail) GetTrimStart() *string {
	if g == nil {
		return nil
	}
	return g.TrimStart
}

func (g *GetMediasMediaIDCustomizationsThumbnailVideoThumbnail) GetTrimEnd() *string {
	if g == nil {
		return nil
	}
	return g.TrimEnd
}

func (g *GetMediasMediaIDCustomizationsThumbnailVideoThumbnail) GetPriorityMode() *string {
	if g == nil {
		return nil
	}
	return g.PriorityMode
}

type GetMediasMediaIDCustomizationsThumbnailThumbnailTextOverlayV2 struct {
	On   *string `json:"on,omitzero"`
	Text *string `json:"text,omitzero"`
}

func (g *GetMediasMediaIDCustomizationsThumbnailThumbnailTextOverlayV2) GetOn() *string {
	if g == nil {
		return nil
	}
	return g.On
}

func (g *GetMediasMediaIDCustomizationsThumbnailThumbnailTextOverlayV2) GetText() *string {
	if g == nil {
		return nil
	}
	return g.Text
}

// #region class-body-getmediasmediaidcustomizationsthumbnailthumbnailtextoverlayv2
// #endregion class-body-getmediasmediaidcustomizationsthumbnailthumbnailtextoverlayv2

type GetMediasMediaIDCustomizationsThumbnailPlugin struct {
	VideoThumbnail         *GetMediasMediaIDCustomizationsThumbnailVideoThumbnail         `json:"videoThumbnail,omitzero"`
	ThumbnailTextOverlayV2 *GetMediasMediaIDCustomizationsThumbnailThumbnailTextOverlayV2 `json:"thumbnailTextOverlay-v2,omitzero"`
}

func (g GetMediasMediaIDCustomizationsThumbnailPlugin) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMediasMediaIDCustomizationsThumbnailPlugin) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMediasMediaIDCustomizationsThumbnailPlugin) GetVideoThumbnail() *GetMediasMediaIDCustomizationsThumbnailVideoThumbnail {
	if g == nil {
		return nil
	}
	return g.VideoThumbnail
}

func (g *GetMediasMediaIDCustomizationsThumbnailPlugin) GetThumbnailTextOverlayV2() *GetMediasMediaIDCustomizationsThumbnailThumbnailTextOverlayV2 {
	if g == nil {
		return nil
	}
	return g.ThumbnailTextOverlayV2
}

// GetMediasMediaIDCustomizationsThumbnailResponseBody - Explicitly-set thumbnail customizations for the video. Values are returned
// as strings (e.g. "true"); fields that have never been set are omitted.
type GetMediasMediaIDCustomizationsThumbnailResponseBody struct {
	StillURL                 *string                                                               `json:"stillUrl,omitzero"`
	ThumbnailAltText         *string                                                               `json:"thumbnailAltText,omitzero"`
	FitStrategy              *string                                                               `json:"fitStrategy,omitzero"`
	UnalteredStillImageAsset *GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnion `json:"unalteredStillImageAsset,omitzero"`
	Plugin                   *GetMediasMediaIDCustomizationsThumbnailPlugin                        `json:"plugin,omitzero"`
}

func (g GetMediasMediaIDCustomizationsThumbnailResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMediasMediaIDCustomizationsThumbnailResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMediasMediaIDCustomizationsThumbnailResponseBody) GetStillURL() *string {
	if g == nil {
		return nil
	}
	return g.StillURL
}

func (g *GetMediasMediaIDCustomizationsThumbnailResponseBody) GetThumbnailAltText() *string {
	if g == nil {
		return nil
	}
	return g.ThumbnailAltText
}

func (g *GetMediasMediaIDCustomizationsThumbnailResponseBody) GetFitStrategy() *string {
	if g == nil {
		return nil
	}
	return g.FitStrategy
}

func (g *GetMediasMediaIDCustomizationsThumbnailResponseBody) GetUnalteredStillImageAsset() *GetMediasMediaIDCustomizationsThumbnailUnalteredStillImageAssetUnion {
	if g == nil {
		return nil
	}
	return g.UnalteredStillImageAsset
}

func (g *GetMediasMediaIDCustomizationsThumbnailResponseBody) GetPlugin() *GetMediasMediaIDCustomizationsThumbnailPlugin {
	if g == nil {
		return nil
	}
	return g.Plugin
}

type GetMediasMediaIDCustomizationsThumbnailResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	Object *GetMediasMediaIDCustomizationsThumbnailResponseBody
}

func (g GetMediasMediaIDCustomizationsThumbnailResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetMediasMediaIDCustomizationsThumbnailResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetMediasMediaIDCustomizationsThumbnailResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetMediasMediaIDCustomizationsThumbnailResponse) GetObject() *GetMediasMediaIDCustomizationsThumbnailResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
