// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 76f97656c0bf

package operations

import (
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
	"github.com/wistia/wistia-cli/internal/sdk/sdkinternal/utils"
)

type GetProjectsProjectIDSharingsSharingIDRequest struct {
	// Hashed ID for the project for which you'd like to see sharings.
	ProjectID string `pathParam:"style=simple,explode=false,name=projectId"`
	// The ID of the specific sharing object that you want to see.
	SharingID int64 `pathParam:"style=simple,explode=false,name=sharingId"`
}

func (g *GetProjectsProjectIDSharingsSharingIDRequest) GetProjectID() string {
	if g == nil {
		return ""
	}
	return g.ProjectID
}

func (g *GetProjectsProjectIDSharingsSharingIDRequest) GetSharingID() int64 {
	if g == nil {
		return 0
	}
	return g.SharingID
}

type GetProjectsProjectIDSharingsSharingIDShare struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Type  string `json:"type"`
	Email string `json:"email"`
}

func (g *GetProjectsProjectIDSharingsSharingIDShare) GetID() int64 {
	if g == nil {
		return 0
	}
	return g.ID
}

func (g *GetProjectsProjectIDSharingsSharingIDShare) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GetProjectsProjectIDSharingsSharingIDShare) GetType() string {
	if g == nil {
		return ""
	}
	return g.Type
}

func (g *GetProjectsProjectIDSharingsSharingIDShare) GetEmail() string {
	if g == nil {
		return ""
	}
	return g.Email
}

type GetProjectsProjectIDSharingsSharingIDProject struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (g *GetProjectsProjectIDSharingsSharingIDProject) GetID() int64 {
	if g == nil {
		return 0
	}
	return g.ID
}

func (g *GetProjectsProjectIDSharingsSharingIDProject) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

// GetProjectsProjectIDSharingsSharingIDResponseBody - Successfully retrieved sharing details
type GetProjectsProjectIDSharingsSharingIDResponseBody struct {
	ID          int64                                        `json:"id"`
	IsAdmin     bool                                         `json:"isAdmin"`
	CanShare    bool                                         `json:"canShare"`
	CanDownload bool                                         `json:"canDownload"`
	CanUpload   bool                                         `json:"canUpload"`
	Share       GetProjectsProjectIDSharingsSharingIDShare   `json:"share"`
	Project     GetProjectsProjectIDSharingsSharingIDProject `json:"project"`
}

func (g *GetProjectsProjectIDSharingsSharingIDResponseBody) GetID() int64 {
	if g == nil {
		return 0
	}
	return g.ID
}

func (g *GetProjectsProjectIDSharingsSharingIDResponseBody) GetIsAdmin() bool {
	if g == nil {
		return false
	}
	return g.IsAdmin
}

func (g *GetProjectsProjectIDSharingsSharingIDResponseBody) GetCanShare() bool {
	if g == nil {
		return false
	}
	return g.CanShare
}

func (g *GetProjectsProjectIDSharingsSharingIDResponseBody) GetCanDownload() bool {
	if g == nil {
		return false
	}
	return g.CanDownload
}

func (g *GetProjectsProjectIDSharingsSharingIDResponseBody) GetCanUpload() bool {
	if g == nil {
		return false
	}
	return g.CanUpload
}

func (g *GetProjectsProjectIDSharingsSharingIDResponseBody) GetShare() GetProjectsProjectIDSharingsSharingIDShare {
	if g == nil {
		return GetProjectsProjectIDSharingsSharingIDShare{}
	}
	return g.Share
}

func (g *GetProjectsProjectIDSharingsSharingIDResponseBody) GetProject() GetProjectsProjectIDSharingsSharingIDProject {
	if g == nil {
		return GetProjectsProjectIDSharingsSharingIDProject{}
	}
	return g.Project
}

type GetProjectsProjectIDSharingsSharingIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successfully retrieved sharing details
	Object *GetProjectsProjectIDSharingsSharingIDResponseBody
}

func (g GetProjectsProjectIDSharingsSharingIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetProjectsProjectIDSharingsSharingIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetProjectsProjectIDSharingsSharingIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetProjectsProjectIDSharingsSharingIDResponse) GetObject() *GetProjectsProjectIDSharingsSharingIDResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
