// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 621172cab793

package operations

import (
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
	"github.com/wistia/wistia-cli/internal/sdk/optionalnullable"
	"github.com/wistia/wistia-cli/internal/sdk/sdkinternal/utils"
)

// PostSpeakersRequest - The reusable speaker profile to add to the account's speaker library.
// Names are not unique: a name that matches an existing profile creates a
// second profile, so look up existing profiles first when the person may
// already be in the library.
type PostSpeakersRequest struct {
	// The speaker's display name. Leading and trailing whitespace is removed.
	Name string `json:"name"`
	// The speaker's title. Leading and trailing whitespace is removed. Omit it, or send null or an empty string, to leave it unset.
	Title optionalnullable.OptionalNullable[string] `json:"title,omitzero"`
}

func (p *PostSpeakersRequest) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PostSpeakersRequest) GetTitle() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Title
}

// PostSpeakersCode - A machine-readable identifier for the specific authorization failure.
type PostSpeakersCode string

const (
	PostSpeakersCodeUnauthorizedCredentials PostSpeakersCode = "unauthorized_credentials"
	PostSpeakersCodeAccountInactive         PostSpeakersCode = "account_inactive"
	PostSpeakersCodeUnauthorizedScope       PostSpeakersCode = "unauthorized_scope"
	PostSpeakersCodeUnauthorizedParams      PostSpeakersCode = "unauthorized_params"
)

func (e PostSpeakersCode) ToPointer() *PostSpeakersCode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PostSpeakersCode) IsExact() bool {
	if e != nil {
		switch *e {
		case "unauthorized_credentials", "account_inactive", "unauthorized_scope", "unauthorized_params":
			return true
		}
	}
	return false
}

// PostSpeakersResponseBody - A reusable speaker profile in the account.
type PostSpeakersResponseBody struct {
	// The unique identifier for this reusable speaker profile.
	SpeakerProfileID string `json:"speaker_profile_id"`
	// The speaker's display name.
	Name string `json:"name"`
	// The speaker's title.
	Title *string `json:"title"`
	// The URL of the speaker's profile image.
	ImageURL *string `json:"image_url"`
	// A cursor for stable pagination based on current `sort_by` order. You can pass this to `cursor[before]` or `cursor[after]` as a parameter to fetch the records before or after this record in the same sort order. This is only populated if records were fetched with `cursor[enabled]`, or `cursor[before]` or `cursor[after]`.
	Cursor optionalnullable.OptionalNullable[string] `json:"cursor,omitzero"`
}

func (p *PostSpeakersResponseBody) GetSpeakerProfileID() string {
	if p == nil {
		return ""
	}
	return p.SpeakerProfileID
}

func (p *PostSpeakersResponseBody) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PostSpeakersResponseBody) GetTitle() *string {
	if p == nil {
		return nil
	}
	return p.Title
}

func (p *PostSpeakersResponseBody) GetImageURL() *string {
	if p == nil {
		return nil
	}
	return p.ImageURL
}

func (p *PostSpeakersResponseBody) GetCursor() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Cursor
}

type PostSpeakersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Speaker profile created successfully
	Object *PostSpeakersResponseBody
}

func (p PostSpeakersResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostSpeakersResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostSpeakersResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostSpeakersResponse) GetObject() *PostSpeakersResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
