// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0c1b24770b8f

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
	"github.com/wistia/wistia-cli/internal/sdk/optionalnullable"
	"github.com/wistia/wistia-cli/internal/sdk/sdkinternal/utils"
	"time"
)

// IetfLanguageTag - IETF language tag for the audio description. Defaults to `eng` (English).
// Non-English orders must set `ai_enabled: false` — AI-generated audio
// descriptions are only available in English.
//
// Spanish (`es-419`) orders are only accepted when the source media is
// tagged as a Spanish-language variant or has no detected language
// (e.g. silent videos). Spanish orders against a media in another
// language return `400`.
type IetfLanguageTag string

const (
	IetfLanguageTagEng   IetfLanguageTag = "eng"
	IetfLanguageTagEs419 IetfLanguageTag = "es-419"
)

func (e IetfLanguageTag) ToPointer() *IetfLanguageTag {
	return &e
}
func (e *IetfLanguageTag) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "eng":
		fallthrough
	case "es-419":
		*e = IetfLanguageTag(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IetfLanguageTag: %v", v)
	}
}

type PostMediaExtendedAudioDescriptionsOrderRequest struct {
	// The hashed id of the media to order the extended audio description for.
	MediaID string `json:"media_id"`
	// Whether the extended audio description should be automatically enabled once the order is complete.
	Enabled *bool `default:"true" json:"enabled"`
	// Whether to use AI-generated audio descriptions (cheaper) or human-generated (higher quality). AI is only available for English orders.
	AiEnabled *bool `default:"true" json:"ai_enabled"`
	// Optional instructions for the audio description provider.
	OrderInstructions *string `json:"order_instructions,omitzero"`
	// IETF language tag for the audio description. Defaults to `eng` (English).
	// Non-English orders must set `ai_enabled: false` — AI-generated audio
	// descriptions are only available in English.
	//
	// Spanish (`es-419`) orders are only accepted when the source media is
	// tagged as a Spanish-language variant or has no detected language
	// (e.g. silent videos). Spanish orders against a media in another
	// language return `400`.
	//
	IetfLanguageTag *IetfLanguageTag `default:"eng" json:"ietf_language_tag"`
}

func (p PostMediaExtendedAudioDescriptionsOrderRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostMediaExtendedAudioDescriptionsOrderRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostMediaExtendedAudioDescriptionsOrderRequest) GetMediaID() string {
	if p == nil {
		return ""
	}
	return p.MediaID
}

func (p *PostMediaExtendedAudioDescriptionsOrderRequest) GetEnabled() *bool {
	if p == nil {
		return nil
	}
	return p.Enabled
}

func (p *PostMediaExtendedAudioDescriptionsOrderRequest) GetAiEnabled() *bool {
	if p == nil {
		return nil
	}
	return p.AiEnabled
}

func (p *PostMediaExtendedAudioDescriptionsOrderRequest) GetOrderInstructions() *string {
	if p == nil {
		return nil
	}
	return p.OrderInstructions
}

func (p *PostMediaExtendedAudioDescriptionsOrderRequest) GetIetfLanguageTag() *IetfLanguageTag {
	if p == nil {
		return nil
	}
	return p.IetfLanguageTag
}

// PostMediaExtendedAudioDescriptionsOrderCode - A machine-readable identifier for the specific authorization failure.
type PostMediaExtendedAudioDescriptionsOrderCode string

const (
	PostMediaExtendedAudioDescriptionsOrderCodeUnauthorizedCredentials PostMediaExtendedAudioDescriptionsOrderCode = "unauthorized_credentials"
	PostMediaExtendedAudioDescriptionsOrderCodeAccountInactive         PostMediaExtendedAudioDescriptionsOrderCode = "account_inactive"
	PostMediaExtendedAudioDescriptionsOrderCodeUnauthorizedScope       PostMediaExtendedAudioDescriptionsOrderCode = "unauthorized_scope"
	PostMediaExtendedAudioDescriptionsOrderCodeUnauthorizedParams      PostMediaExtendedAudioDescriptionsOrderCode = "unauthorized_params"
)

func (e PostMediaExtendedAudioDescriptionsOrderCode) ToPointer() *PostMediaExtendedAudioDescriptionsOrderCode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PostMediaExtendedAudioDescriptionsOrderCode) IsExact() bool {
	if e != nil {
		switch *e {
		case "unauthorized_credentials", "account_inactive", "unauthorized_scope", "unauthorized_params":
			return true
		}
	}
	return false
}

// PostMediaExtendedAudioDescriptionsOrderOrderStatus - The current status of the order.
type PostMediaExtendedAudioDescriptionsOrderOrderStatus string

const (
	PostMediaExtendedAudioDescriptionsOrderOrderStatusInProgress PostMediaExtendedAudioDescriptionsOrderOrderStatus = "in_progress"
	PostMediaExtendedAudioDescriptionsOrderOrderStatusCompleted  PostMediaExtendedAudioDescriptionsOrderOrderStatus = "completed"
	PostMediaExtendedAudioDescriptionsOrderOrderStatusCancelled  PostMediaExtendedAudioDescriptionsOrderOrderStatus = "cancelled"
	PostMediaExtendedAudioDescriptionsOrderOrderStatusFailed     PostMediaExtendedAudioDescriptionsOrderOrderStatus = "failed"
)

func (e PostMediaExtendedAudioDescriptionsOrderOrderStatus) ToPointer() *PostMediaExtendedAudioDescriptionsOrderOrderStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PostMediaExtendedAudioDescriptionsOrderOrderStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "in_progress", "completed", "cancelled", "failed":
			return true
		}
	}
	return false
}

type PostMediaExtendedAudioDescriptionsOrderMedia struct {
	// A unique alphanumeric identifier for the record.
	ID string `json:"id"`
	// A URL for fetching all the records of the given record type. You can pass hashed_ids as a param with multiple values
	// to do a batch fetch for this records type.
	//
	IndexURL string `json:"index_url"`
	// A URL that can be used to fetch this record.
	URL string `json:"url"`
}

func (p *PostMediaExtendedAudioDescriptionsOrderMedia) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PostMediaExtendedAudioDescriptionsOrderMedia) GetIndexURL() string {
	if p == nil {
		return ""
	}
	return p.IndexURL
}

func (p *PostMediaExtendedAudioDescriptionsOrderMedia) GetURL() string {
	if p == nil {
		return ""
	}
	return p.URL
}

type PostMediaExtendedAudioDescriptionsOrderMediaExtendedAudioDescription struct {
	// A unique alphanumeric identifier for the record.
	ID string `json:"id"`
	// A URL for fetching all the records of the given record type. You can pass hashed_ids as a param with multiple values
	// to do a batch fetch for this records type.
	//
	IndexURL string `json:"index_url"`
	// A URL that can be used to fetch this record.
	URL string `json:"url"`
}

func (p *PostMediaExtendedAudioDescriptionsOrderMediaExtendedAudioDescription) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PostMediaExtendedAudioDescriptionsOrderMediaExtendedAudioDescription) GetIndexURL() string {
	if p == nil {
		return ""
	}
	return p.IndexURL
}

func (p *PostMediaExtendedAudioDescriptionsOrderMediaExtendedAudioDescription) GetURL() string {
	if p == nil {
		return ""
	}
	return p.URL
}

type PostMediaExtendedAudioDescriptionsOrderOrder struct {
	// The hashed ID of the order. Use this to poll order status via the order_status endpoint.
	ID string `json:"id"`
	// The current status of the order.
	OrderStatus PostMediaExtendedAudioDescriptionsOrderOrderStatus `json:"order_status"`
	CreatedAt   time.Time                                          `json:"created_at"`
	UpdatedAt   time.Time                                          `json:"updated_at"`
	// IETF language tag the audio description was ordered in (e.g. `eng`, `es-419`).
	IetfLanguageTag string                                       `json:"ietf_language_tag"`
	Media           PostMediaExtendedAudioDescriptionsOrderMedia `json:"media"`
	// Link to the resulting media extended audio description. Null while the order is in progress.
	MediaExtendedAudioDescription optionalnullable.OptionalNullable[PostMediaExtendedAudioDescriptionsOrderMediaExtendedAudioDescription] `json:"media_extended_audio_description,omitzero"`
}

func (p PostMediaExtendedAudioDescriptionsOrderOrder) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostMediaExtendedAudioDescriptionsOrderOrder) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostMediaExtendedAudioDescriptionsOrderOrder) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PostMediaExtendedAudioDescriptionsOrderOrder) GetOrderStatus() PostMediaExtendedAudioDescriptionsOrderOrderStatus {
	if p == nil {
		return PostMediaExtendedAudioDescriptionsOrderOrderStatus("")
	}
	return p.OrderStatus
}

func (p *PostMediaExtendedAudioDescriptionsOrderOrder) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *PostMediaExtendedAudioDescriptionsOrderOrder) GetUpdatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.UpdatedAt
}

func (p *PostMediaExtendedAudioDescriptionsOrderOrder) GetIetfLanguageTag() string {
	if p == nil {
		return ""
	}
	return p.IetfLanguageTag
}

func (p *PostMediaExtendedAudioDescriptionsOrderOrder) GetMedia() PostMediaExtendedAudioDescriptionsOrderMedia {
	if p == nil {
		return PostMediaExtendedAudioDescriptionsOrderMedia{}
	}
	return p.Media
}

func (p *PostMediaExtendedAudioDescriptionsOrderOrder) GetMediaExtendedAudioDescription() optionalnullable.OptionalNullable[PostMediaExtendedAudioDescriptionsOrderMediaExtendedAudioDescription] {
	if p == nil {
		return nil
	}
	return p.MediaExtendedAudioDescription
}

// PostMediaExtendedAudioDescriptionsOrderResponseBody - Extended audio description ordered successfully.
type PostMediaExtendedAudioDescriptionsOrderResponseBody struct {
	// Success message indicating the order has been placed.
	Message string                                       `json:"message"`
	Order   PostMediaExtendedAudioDescriptionsOrderOrder `json:"order"`
	// The credits held for the audio description, deducted when it completes. Null when the audio description is not paid for with credits. Decimal amounts are returned as strings.
	ExpectedBilledCredits *string `json:"expected_billed_credits"`
}

func (p *PostMediaExtendedAudioDescriptionsOrderResponseBody) GetMessage() string {
	if p == nil {
		return ""
	}
	return p.Message
}

func (p *PostMediaExtendedAudioDescriptionsOrderResponseBody) GetOrder() PostMediaExtendedAudioDescriptionsOrderOrder {
	if p == nil {
		return PostMediaExtendedAudioDescriptionsOrderOrder{}
	}
	return p.Order
}

func (p *PostMediaExtendedAudioDescriptionsOrderResponseBody) GetExpectedBilledCredits() *string {
	if p == nil {
		return nil
	}
	return p.ExpectedBilledCredits
}

type PostMediaExtendedAudioDescriptionsOrderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Extended audio description ordered successfully.
	Object *PostMediaExtendedAudioDescriptionsOrderResponseBody
}

func (p PostMediaExtendedAudioDescriptionsOrderResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostMediaExtendedAudioDescriptionsOrderResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostMediaExtendedAudioDescriptionsOrderResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostMediaExtendedAudioDescriptionsOrderResponse) GetObject() *PostMediaExtendedAudioDescriptionsOrderResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
