// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 01779b40f317

package operations

import (
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
	"github.com/wistia/wistia-cli/internal/sdk/sdkinternal/utils"
)

type PostTaggingsBulkCreateRequest struct {
	// An array of the media hashed IDs to be tagged.
	HashedIds []string `json:"hashed_ids"`
	// An array of tag names to add to each media.
	TagNames []string `json:"tag_names"`
}

func (p *PostTaggingsBulkCreateRequest) GetHashedIds() []string {
	if p == nil {
		return []string{}
	}
	return p.HashedIds
}

func (p *PostTaggingsBulkCreateRequest) GetTagNames() []string {
	if p == nil {
		return []string{}
	}
	return p.TagNames
}

// PostTaggingsBulkCreateCode - A machine-readable identifier for the specific authorization failure.
type PostTaggingsBulkCreateCode string

const (
	PostTaggingsBulkCreateCodeUnauthorizedCredentials PostTaggingsBulkCreateCode = "unauthorized_credentials"
	PostTaggingsBulkCreateCodeAccountInactive         PostTaggingsBulkCreateCode = "account_inactive"
	PostTaggingsBulkCreateCodeUnauthorizedScope       PostTaggingsBulkCreateCode = "unauthorized_scope"
	PostTaggingsBulkCreateCodeUnauthorizedParams      PostTaggingsBulkCreateCode = "unauthorized_params"
)

func (e PostTaggingsBulkCreateCode) ToPointer() *PostTaggingsBulkCreateCode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PostTaggingsBulkCreateCode) IsExact() bool {
	if e != nil {
		switch *e {
		case "unauthorized_credentials", "account_inactive", "unauthorized_scope", "unauthorized_params":
			return true
		}
	}
	return false
}

// PostTaggingsBulkCreateStatus - The status of the background job that's been queued for the request.
type PostTaggingsBulkCreateStatus string

const (
	PostTaggingsBulkCreateStatusQueued   PostTaggingsBulkCreateStatus = "queued"
	PostTaggingsBulkCreateStatusStarted  PostTaggingsBulkCreateStatus = "started"
	PostTaggingsBulkCreateStatusFinished PostTaggingsBulkCreateStatus = "finished"
	PostTaggingsBulkCreateStatusFailed   PostTaggingsBulkCreateStatus = "failed"
)

func (e PostTaggingsBulkCreateStatus) ToPointer() *PostTaggingsBulkCreateStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PostTaggingsBulkCreateStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "queued", "started", "finished", "failed":
			return true
		}
	}
	return false
}

// PostTaggingsBulkCreateBackgroundJobStatus - A background job keeps track of the progress of an asynchronous task, e.g
// bulk archiving media, translating media, etc.
type PostTaggingsBulkCreateBackgroundJobStatus struct {
	// The ID of the background job that's been queued for the request.
	ID int64 `json:"id"`
	// The unguessable hashed ID of the background job. Prefer this over the numeric ID when polling for status.
	HashedID string `json:"hashed_id"`
	// The status of the background job that's been queued for the request.
	Status PostTaggingsBulkCreateStatus `json:"status"`
}

func (p *PostTaggingsBulkCreateBackgroundJobStatus) GetID() int64 {
	if p == nil {
		return 0
	}
	return p.ID
}

func (p *PostTaggingsBulkCreateBackgroundJobStatus) GetHashedID() string {
	if p == nil {
		return ""
	}
	return p.HashedID
}

func (p *PostTaggingsBulkCreateBackgroundJobStatus) GetStatus() PostTaggingsBulkCreateStatus {
	if p == nil {
		return PostTaggingsBulkCreateStatus("")
	}
	return p.Status
}

// PostTaggingsBulkCreateResponseBody - Successful tagging of media.
type PostTaggingsBulkCreateResponseBody struct {
	// A confirmation message that the background job has been queued.
	Message *string `json:"message,omitzero"`
	// A background job keeps track of the progress of an asynchronous task, e.g
	// bulk archiving media, translating media, etc.
	//
	BackgroundJobStatus *PostTaggingsBulkCreateBackgroundJobStatus `json:"background_job_status,omitzero"`
}

func (p PostTaggingsBulkCreateResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostTaggingsBulkCreateResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostTaggingsBulkCreateResponseBody) GetMessage() *string {
	if p == nil {
		return nil
	}
	return p.Message
}

func (p *PostTaggingsBulkCreateResponseBody) GetBackgroundJobStatus() *PostTaggingsBulkCreateBackgroundJobStatus {
	if p == nil {
		return nil
	}
	return p.BackgroundJobStatus
}

type PostTaggingsBulkCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful tagging of media.
	Object *PostTaggingsBulkCreateResponseBody
}

func (p PostTaggingsBulkCreateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostTaggingsBulkCreateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostTaggingsBulkCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostTaggingsBulkCreateResponse) GetObject() *PostTaggingsBulkCreateResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
