// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: dd56a17287c0

package operations

import (
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
	"github.com/wistia/wistia-cli/internal/sdk/optionalnullable"
	"github.com/wistia/wistia-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type PostProjectsIDCopyRequestBody struct {
	// The email address of the account Manager that will be the owner of the new project. Defaults to the Account Owner if invalid or omitted.
	AdminEmail *string `json:"adminEmail,omitzero"`
}

func (p *PostProjectsIDCopyRequestBody) GetAdminEmail() *string {
	if p == nil {
		return nil
	}
	return p.AdminEmail
}

type PostProjectsIDCopyRequest struct {
	// Project Hashed ID
	ID   string                         `pathParam:"style=simple,explode=false,name=id"`
	Body *PostProjectsIDCopyRequestBody `request:"mediaType=application/json"`
}

func (p PostProjectsIDCopyRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostProjectsIDCopyRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostProjectsIDCopyRequest) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PostProjectsIDCopyRequest) GetBody() *PostProjectsIDCopyRequestBody {
	if p == nil {
		return nil
	}
	return p.Body
}

// PostProjectsIDCopyResponseBody - Project copied successfully
type PostProjectsIDCopyResponseBody struct {
	// A unique numeric identifier for the project within the system.
	ID int64 `json:"id"`
	// The project’s display name.
	Name string `json:"name"`
	// The project’s description.
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	// The number of different medias that have been uploaded to the project.
	MediaCount int64 `json:"mediaCount"`
	// The date that the project was originally created.
	Created time.Time `json:"created"`
	// The date that the project was last updated.
	Updated time.Time `json:"updated"`
	// A private hashed id, uniquely identifying the project within the system.
	HashedID string `json:"hashedId"`
	// A boolean indicating whether the project is available for public (anonymous) viewing.
	Public bool `json:"public"`
	// If the project is public, this field contains a string representing the ID used for referencing the project in public URLs.
	PublicID             *string `json:"publicId"`
	AnonymousCanUpload   *bool   `json:"anonymousCanUpload,omitzero"`
	AnonymousCanDownload *bool   `json:"anonymousCanDownload,omitzero"`
}

func (p PostProjectsIDCopyResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostProjectsIDCopyResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostProjectsIDCopyResponseBody) GetID() int64 {
	if p == nil {
		return 0
	}
	return p.ID
}

func (p *PostProjectsIDCopyResponseBody) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PostProjectsIDCopyResponseBody) GetDescription() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PostProjectsIDCopyResponseBody) GetMediaCount() int64 {
	if p == nil {
		return 0
	}
	return p.MediaCount
}

func (p *PostProjectsIDCopyResponseBody) GetCreated() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.Created
}

func (p *PostProjectsIDCopyResponseBody) GetUpdated() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.Updated
}

func (p *PostProjectsIDCopyResponseBody) GetHashedID() string {
	if p == nil {
		return ""
	}
	return p.HashedID
}

func (p *PostProjectsIDCopyResponseBody) GetPublic() bool {
	if p == nil {
		return false
	}
	return p.Public
}

func (p *PostProjectsIDCopyResponseBody) GetPublicID() *string {
	if p == nil {
		return nil
	}
	return p.PublicID
}

func (p *PostProjectsIDCopyResponseBody) GetAnonymousCanUpload() *bool {
	if p == nil {
		return nil
	}
	return p.AnonymousCanUpload
}

func (p *PostProjectsIDCopyResponseBody) GetAnonymousCanDownload() *bool {
	if p == nil {
		return nil
	}
	return p.AnonymousCanDownload
}

type PostProjectsIDCopyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Project copied successfully
	Object  *PostProjectsIDCopyResponseBody
	Headers map[string][]string
}

func (p PostProjectsIDCopyResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostProjectsIDCopyResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostProjectsIDCopyResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostProjectsIDCopyResponse) GetObject() *PostProjectsIDCopyResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}

func (p *PostProjectsIDCopyResponse) GetHeaders() map[string][]string {
	if p == nil {
		return map[string][]string{}
	}
	return p.Headers
}
