// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
	"github.com/wistia/wistia-cli/internal/sdk/optionalnullable"
	"github.com/wistia/wistia-cli/internal/sdk/sdkinternal/utils"
	"time"
)

type LiveStreamEvent struct {
	// The title of the live stream event
	Title *string `json:"title,omitzero"`
	// The description of the live stream event
	Description *string `json:"description,omitzero"`
	// The scheduled start time in W3C format with timezone
	ScheduledFor *time.Time `json:"scheduled_for,omitzero"`
	// Duration of the event in minutes (minimum 15)
	EventDuration *int64 `json:"event_duration,omitzero"`
}

func (l LiveStreamEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LiveStreamEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *LiveStreamEvent) GetTitle() *string {
	if l == nil {
		return nil
	}
	return l.Title
}

func (l *LiveStreamEvent) GetDescription() *string {
	if l == nil {
		return nil
	}
	return l.Description
}

func (l *LiveStreamEvent) GetScheduledFor() *time.Time {
	if l == nil {
		return nil
	}
	return l.ScheduledFor
}

func (l *LiveStreamEvent) GetEventDuration() *int64 {
	if l == nil {
		return nil
	}
	return l.EventDuration
}

type PutLiveStreamEventsIDRequestBody struct {
	LiveStreamEvent *LiveStreamEvent `json:"live_stream_event,omitzero"`
}

func (p PutLiveStreamEventsIDRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PutLiveStreamEventsIDRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PutLiveStreamEventsIDRequestBody) GetLiveStreamEvent() *LiveStreamEvent {
	if p == nil {
		return nil
	}
	return p.LiveStreamEvent
}

type PutLiveStreamEventsIDRequest struct {
	// The hashed ID of the live stream event
	ID   string                           `pathParam:"style=simple,explode=false,name=id"`
	Body PutLiveStreamEventsIDRequestBody `request:"mediaType=application/json"`
}

func (p *PutLiveStreamEventsIDRequest) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PutLiveStreamEventsIDRequest) GetBody() PutLiveStreamEventsIDRequestBody {
	if p == nil {
		return PutLiveStreamEventsIDRequestBody{}
	}
	return p.Body
}

// PutLiveStreamEventsIDResponseBody - Live stream event updated successfully
type PutLiveStreamEventsIDResponseBody struct {
	// The hashed ID of the live stream event
	ID string `json:"id"`
	// The title of the live stream event
	Title string `json:"title"`
	// The description of the live stream event
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	// The scheduled start time in W3C format with timezone
	ScheduledFor optionalnullable.OptionalNullable[time.Time] `json:"scheduled_for,omitzero"`
	// Duration of the event in minutes
	EventDuration optionalnullable.OptionalNullable[int64] `json:"event_duration,omitzero"`
	// Current lifecycle status of the event
	LifecycleStatus string `json:"lifecycle_status"`
	// Registration status of the event
	RegistrationStatus string `json:"registration_status"`
	// When the event was created (UTC)
	CreatedAt time.Time `json:"created_at"`
	// When the event was last updated (UTC)
	UpdatedAt time.Time `json:"updated_at"`
	// Link for the audience to join the event
	AudienceLink string `json:"audience_link"`
	// Link for the host to manage the event
	HostLink string `json:"host_link"`
}

func (p PutLiveStreamEventsIDResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PutLiveStreamEventsIDResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PutLiveStreamEventsIDResponseBody) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PutLiveStreamEventsIDResponseBody) GetTitle() string {
	if p == nil {
		return ""
	}
	return p.Title
}

func (p *PutLiveStreamEventsIDResponseBody) GetDescription() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PutLiveStreamEventsIDResponseBody) GetScheduledFor() optionalnullable.OptionalNullable[time.Time] {
	if p == nil {
		return nil
	}
	return p.ScheduledFor
}

func (p *PutLiveStreamEventsIDResponseBody) GetEventDuration() optionalnullable.OptionalNullable[int64] {
	if p == nil {
		return nil
	}
	return p.EventDuration
}

func (p *PutLiveStreamEventsIDResponseBody) GetLifecycleStatus() string {
	if p == nil {
		return ""
	}
	return p.LifecycleStatus
}

func (p *PutLiveStreamEventsIDResponseBody) GetRegistrationStatus() string {
	if p == nil {
		return ""
	}
	return p.RegistrationStatus
}

func (p *PutLiveStreamEventsIDResponseBody) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *PutLiveStreamEventsIDResponseBody) GetUpdatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.UpdatedAt
}

func (p *PutLiveStreamEventsIDResponseBody) GetAudienceLink() string {
	if p == nil {
		return ""
	}
	return p.AudienceLink
}

func (p *PutLiveStreamEventsIDResponseBody) GetHostLink() string {
	if p == nil {
		return ""
	}
	return p.HostLink
}

type PutLiveStreamEventsIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Live stream event updated successfully
	Object *PutLiveStreamEventsIDResponseBody
}

func (p PutLiveStreamEventsIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PutLiveStreamEventsIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PutLiveStreamEventsIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PutLiveStreamEventsIDResponse) GetObject() *PutLiveStreamEventsIDResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
