// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 724cca731533

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
	"github.com/wistia/wistia-cli/internal/sdk/sdkinternal/utils"
	"time"
)

// VisibilityRequest - Controls who can view the media via this share link.
//
//   - `unlocked`: anyone with the link can view the media.
//   - `account`: only signed-in members of the media's account can view.
//   - `locked`: only contacts with access to the media's folder can view.
//   - `domain_verified`: only viewers signed in with an email address at a
//     domain verified on the media's account can view. Requires the account
//     to be enrolled in the domain validation gate; otherwise setting this
//     value returns 400.
type VisibilityRequest string

const (
	VisibilityRequestUnlocked       VisibilityRequest = "unlocked"
	VisibilityRequestAccount        VisibilityRequest = "account"
	VisibilityRequestLocked         VisibilityRequest = "locked"
	VisibilityRequestDomainVerified VisibilityRequest = "domain_verified"
)

func (e VisibilityRequest) ToPointer() *VisibilityRequest {
	return &e
}
func (e *VisibilityRequest) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "unlocked":
		fallthrough
	case "account":
		fallthrough
	case "locked":
		fallthrough
	case "domain_verified":
		*e = VisibilityRequest(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VisibilityRequest: %v", v)
	}
}

// PutMediasMediaIDShareLinkRequestBody - Fields that can be set when updating a share link.
type PutMediasMediaIDShareLinkRequestBody struct {
	// Controls who can view the media via this share link.
	//
	// - `unlocked`: anyone with the link can view the media.
	// - `account`: only signed-in members of the media's account can view.
	// - `locked`: only contacts with access to the media's folder can view.
	// - `domain_verified`: only viewers signed in with an email address at a
	//   domain verified on the media's account can view. Requires the account
	//   to be enrolled in the domain validation gate; otherwise setting this
	//   value returns 400.
	//
	Visibility VisibilityRequest `json:"visibility"`
}

func (p *PutMediasMediaIDShareLinkRequestBody) GetVisibility() VisibilityRequest {
	if p == nil {
		return VisibilityRequest("")
	}
	return p.Visibility
}

type PutMediasMediaIDShareLinkRequest struct {
	// The hashed ID of the media.
	MediaID string                               `pathParam:"style=simple,explode=false,name=mediaId"`
	Body    PutMediasMediaIDShareLinkRequestBody `request:"mediaType=application/json"`
}

func (p *PutMediasMediaIDShareLinkRequest) GetMediaID() string {
	if p == nil {
		return ""
	}
	return p.MediaID
}

func (p *PutMediasMediaIDShareLinkRequest) GetBody() PutMediasMediaIDShareLinkRequestBody {
	if p == nil {
		return PutMediasMediaIDShareLinkRequestBody{}
	}
	return p.Body
}

// PutMediasMediaIDShareLinkCode - A machine-readable identifier for the specific authorization failure.
type PutMediasMediaIDShareLinkCode string

const (
	PutMediasMediaIDShareLinkCodeUnauthorizedCredentials PutMediasMediaIDShareLinkCode = "unauthorized_credentials"
	PutMediasMediaIDShareLinkCodeAccountInactive         PutMediasMediaIDShareLinkCode = "account_inactive"
	PutMediasMediaIDShareLinkCodeUnauthorizedScope       PutMediasMediaIDShareLinkCode = "unauthorized_scope"
	PutMediasMediaIDShareLinkCodeUnauthorizedParams      PutMediasMediaIDShareLinkCode = "unauthorized_params"
)

func (e PutMediasMediaIDShareLinkCode) ToPointer() *PutMediasMediaIDShareLinkCode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PutMediasMediaIDShareLinkCode) IsExact() bool {
	if e != nil {
		switch *e {
		case "unauthorized_credentials", "account_inactive", "unauthorized_scope", "unauthorized_params":
			return true
		}
	}
	return false
}

// PutMediasMediaIDShareLinkVisibilityResponse - Controls who can view the media via this share link.
//
//   - `unlocked`: anyone with the link can view the media.
//   - `account`: only signed-in members of the media's account can view.
//   - `locked`: only contacts with access to the media's folder can view.
//   - `domain_verified`: only viewers signed in with an email address at a
//     domain verified on the media's account can view. Requires the account
//     to be enrolled in the domain validation gate; otherwise setting this
//     value returns 400.
type PutMediasMediaIDShareLinkVisibilityResponse string

const (
	PutMediasMediaIDShareLinkVisibilityResponseUnlocked       PutMediasMediaIDShareLinkVisibilityResponse = "unlocked"
	PutMediasMediaIDShareLinkVisibilityResponseAccount        PutMediasMediaIDShareLinkVisibilityResponse = "account"
	PutMediasMediaIDShareLinkVisibilityResponseLocked         PutMediasMediaIDShareLinkVisibilityResponse = "locked"
	PutMediasMediaIDShareLinkVisibilityResponseDomainVerified PutMediasMediaIDShareLinkVisibilityResponse = "domain_verified"
)

func (e PutMediasMediaIDShareLinkVisibilityResponse) ToPointer() *PutMediasMediaIDShareLinkVisibilityResponse {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PutMediasMediaIDShareLinkVisibilityResponse) IsExact() bool {
	if e != nil {
		switch *e {
		case "unlocked", "account", "locked", "domain_verified":
			return true
		}
	}
	return false
}

// PutMediasMediaIDShareLinkResponseBody - A shareable link for a single media. Each media can have at most one
// share link, and the link's `visibility` controls who can view the
// media when visiting the link.
type PutMediasMediaIDShareLinkResponseBody struct {
	// The hashed ID of the share link. This appears in the link's URL.
	ID string `json:"id"`
	// The hashed ID of the media this share link points to.
	MediaID string `json:"media_id"`
	// The full URL viewers can use to view the media via this share link.
	URL string `json:"url"`
	// Controls who can view the media via this share link.
	//
	// - `unlocked`: anyone with the link can view the media.
	// - `account`: only signed-in members of the media's account can view.
	// - `locked`: only contacts with access to the media's folder can view.
	// - `domain_verified`: only viewers signed in with an email address at a
	//   domain verified on the media's account can view. Requires the account
	//   to be enrolled in the domain validation gate; otherwise setting this
	//   value returns 400.
	//
	Visibility PutMediasMediaIDShareLinkVisibilityResponse `json:"visibility"`
	// When the share link was created.
	CreatedAt time.Time `json:"created_at"`
	// When the share link was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

func (p PutMediasMediaIDShareLinkResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PutMediasMediaIDShareLinkResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PutMediasMediaIDShareLinkResponseBody) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PutMediasMediaIDShareLinkResponseBody) GetMediaID() string {
	if p == nil {
		return ""
	}
	return p.MediaID
}

func (p *PutMediasMediaIDShareLinkResponseBody) GetURL() string {
	if p == nil {
		return ""
	}
	return p.URL
}

func (p *PutMediasMediaIDShareLinkResponseBody) GetVisibility() PutMediasMediaIDShareLinkVisibilityResponse {
	if p == nil {
		return PutMediasMediaIDShareLinkVisibilityResponse("")
	}
	return p.Visibility
}

func (p *PutMediasMediaIDShareLinkResponseBody) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *PutMediasMediaIDShareLinkResponseBody) GetUpdatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.UpdatedAt
}

type PutMediasMediaIDShareLinkResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Share link update successful
	Object *PutMediasMediaIDShareLinkResponseBody
}

func (p PutMediasMediaIDShareLinkResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PutMediasMediaIDShareLinkResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PutMediasMediaIDShareLinkResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PutMediasMediaIDShareLinkResponse) GetObject() *PutMediasMediaIDShareLinkResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
