// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b9ea7fe86a3c

package operations

import (
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
	"github.com/wistia/wistia-cli/internal/sdk/sdkinternal/utils"
)

type PutMediasArchiveRequest struct {
	// An array of the media hashed IDs to be archived.
	HashedIds []string `json:"hashed_ids"`
}

func (p *PutMediasArchiveRequest) GetHashedIds() []string {
	if p == nil {
		return []string{}
	}
	return p.HashedIds
}

// PutMediasArchiveCode - A machine-readable identifier for the specific authorization failure.
type PutMediasArchiveCode string

const (
	PutMediasArchiveCodeUnauthorizedCredentials PutMediasArchiveCode = "unauthorized_credentials"
	PutMediasArchiveCodeAccountInactive         PutMediasArchiveCode = "account_inactive"
	PutMediasArchiveCodeUnauthorizedScope       PutMediasArchiveCode = "unauthorized_scope"
	PutMediasArchiveCodeUnauthorizedParams      PutMediasArchiveCode = "unauthorized_params"
)

func (e PutMediasArchiveCode) ToPointer() *PutMediasArchiveCode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PutMediasArchiveCode) IsExact() bool {
	if e != nil {
		switch *e {
		case "unauthorized_credentials", "account_inactive", "unauthorized_scope", "unauthorized_params":
			return true
		}
	}
	return false
}

// PutMediasArchiveStatus - The status of the background job that's been queued for the request.
type PutMediasArchiveStatus string

const (
	PutMediasArchiveStatusQueued   PutMediasArchiveStatus = "queued"
	PutMediasArchiveStatusStarted  PutMediasArchiveStatus = "started"
	PutMediasArchiveStatusFinished PutMediasArchiveStatus = "finished"
	PutMediasArchiveStatusFailed   PutMediasArchiveStatus = "failed"
)

func (e PutMediasArchiveStatus) ToPointer() *PutMediasArchiveStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PutMediasArchiveStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "queued", "started", "finished", "failed":
			return true
		}
	}
	return false
}

// PutMediasArchiveBackgroundJobStatus - A background job keeps track of the progress of an asynchronous task, e.g
// bulk archiving media, translating media, etc.
type PutMediasArchiveBackgroundJobStatus struct {
	// The ID of the background job that's been queued for the request.
	ID int64 `json:"id"`
	// The unguessable hashed ID of the background job. Prefer this over the numeric ID when polling for status.
	HashedID string `json:"hashed_id"`
	// The status of the background job that's been queued for the request.
	Status PutMediasArchiveStatus `json:"status"`
}

func (p *PutMediasArchiveBackgroundJobStatus) GetID() int64 {
	if p == nil {
		return 0
	}
	return p.ID
}

func (p *PutMediasArchiveBackgroundJobStatus) GetHashedID() string {
	if p == nil {
		return ""
	}
	return p.HashedID
}

func (p *PutMediasArchiveBackgroundJobStatus) GetStatus() PutMediasArchiveStatus {
	if p == nil {
		return PutMediasArchiveStatus("")
	}
	return p.Status
}

// PutMediasArchiveResponseBody - Successful archival of media.
type PutMediasArchiveResponseBody struct {
	// A confirmation message that the background job has been queued.
	Message *string `json:"message,omitzero"`
	// A background job keeps track of the progress of an asynchronous task, e.g
	// bulk archiving media, translating media, etc.
	//
	BackgroundJobStatus *PutMediasArchiveBackgroundJobStatus `json:"background_job_status,omitzero"`
}

func (p PutMediasArchiveResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PutMediasArchiveResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PutMediasArchiveResponseBody) GetMessage() *string {
	if p == nil {
		return nil
	}
	return p.Message
}

func (p *PutMediasArchiveResponseBody) GetBackgroundJobStatus() *PutMediasArchiveBackgroundJobStatus {
	if p == nil {
		return nil
	}
	return p.BackgroundJobStatus
}

type PutMediasArchiveResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful archival of media.
	Object *PutMediasArchiveResponseBody
}

func (p PutMediasArchiveResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PutMediasArchiveResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PutMediasArchiveResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PutMediasArchiveResponse) GetObject() *PutMediasArchiveResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
