// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
	"github.com/wistia/wistia-cli/internal/sdk/optionalnullable"
	"github.com/wistia/wistia-cli/internal/sdk/sdkinternal/utils"
	"time"
)

// PutProjectsIDPublicEnum - A flag indicating whether or not the project is enabled for public access. Set to “1” to enable and “0” to disable.
type PutProjectsIDPublicEnum string

const (
	PutProjectsIDPublicEnumZero PutProjectsIDPublicEnum = "0"
	PutProjectsIDPublicEnumOne  PutProjectsIDPublicEnum = "1"
)

func (e PutProjectsIDPublicEnum) ToPointer() *PutProjectsIDPublicEnum {
	return &e
}
func (e *PutProjectsIDPublicEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "0":
		fallthrough
	case "1":
		*e = PutProjectsIDPublicEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PutProjectsIDPublicEnum: %v", v)
	}
}

type PutProjectsIDPublicUnionType string

const (
	PutProjectsIDPublicUnionTypePutProjectsIDPublicEnum PutProjectsIDPublicUnionType = "put_projects_id__public_enum"
	PutProjectsIDPublicUnionTypeBoolean                 PutProjectsIDPublicUnionType = "boolean"
)

type PutProjectsIDPublicUnion struct {
	PutProjectsIDPublicEnum *PutProjectsIDPublicEnum `queryParam:"inline" union:"member"`
	Boolean                 *bool                    `queryParam:"inline" union:"member"`

	Type PutProjectsIDPublicUnionType
}

func CreatePutProjectsIDPublicUnionPutProjectsIDPublicEnum(putProjectsIDPublicEnum PutProjectsIDPublicEnum) PutProjectsIDPublicUnion {
	typ := PutProjectsIDPublicUnionTypePutProjectsIDPublicEnum

	return PutProjectsIDPublicUnion{
		PutProjectsIDPublicEnum: &putProjectsIDPublicEnum,
		Type:                    typ,
	}
}

func CreatePutProjectsIDPublicUnionBoolean(boolean bool) PutProjectsIDPublicUnion {
	typ := PutProjectsIDPublicUnionTypeBoolean

	return PutProjectsIDPublicUnion{
		Boolean: &boolean,
		Type:    typ,
	}
}

func (u *PutProjectsIDPublicUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var putProjectsIDPublicEnum PutProjectsIDPublicEnum = PutProjectsIDPublicEnum("")
	if err := utils.UnmarshalJSON(data, &putProjectsIDPublicEnum, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  PutProjectsIDPublicUnionTypePutProjectsIDPublicEnum,
			Value: &putProjectsIDPublicEnum,
		})
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  PutProjectsIDPublicUnionTypeBoolean,
			Value: &boolean,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for PutProjectsIDPublicUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for PutProjectsIDPublicUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(PutProjectsIDPublicUnionType)
	switch best.Type {
	case PutProjectsIDPublicUnionTypePutProjectsIDPublicEnum:
		u.PutProjectsIDPublicEnum = best.Value.(*PutProjectsIDPublicEnum)
		return nil
	case PutProjectsIDPublicUnionTypeBoolean:
		u.Boolean = best.Value.(*bool)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for PutProjectsIDPublicUnion", string(data))
}

func (u PutProjectsIDPublicUnion) MarshalJSON() ([]byte, error) {
	if u.PutProjectsIDPublicEnum != nil {
		return utils.MarshalJSON(u.PutProjectsIDPublicEnum, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	return nil, errors.New("could not marshal union type PutProjectsIDPublicUnion: all fields are null")
}

type PutProjectsIDRequestBody struct {
	// The project’s new name.
	Name *string `json:"name,omitzero"`
	// The project’s new description.
	Description *string `json:"description,omitzero"`
	// Whether anonymous users can upload media to the project.
	AnonymousCanUpload *bool `json:"anonymousCanUpload,omitzero"`
	// Whether anonymous users can download media from the project.
	AnonymousCanDownload *bool                     `json:"anonymousCanDownload,omitzero"`
	Public               *PutProjectsIDPublicUnion `json:"public,omitzero"`
}

func (p *PutProjectsIDRequestBody) GetName() *string {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *PutProjectsIDRequestBody) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PutProjectsIDRequestBody) GetAnonymousCanUpload() *bool {
	if p == nil {
		return nil
	}
	return p.AnonymousCanUpload
}

func (p *PutProjectsIDRequestBody) GetAnonymousCanDownload() *bool {
	if p == nil {
		return nil
	}
	return p.AnonymousCanDownload
}

func (p *PutProjectsIDRequestBody) GetPublic() *PutProjectsIDPublicUnion {
	if p == nil {
		return nil
	}
	return p.Public
}

type PutProjectsIDRequest struct {
	// Project Hashed ID
	ID   string                    `pathParam:"style=simple,explode=false,name=id"`
	Body *PutProjectsIDRequestBody `request:"mediaType=application/json"`
}

func (p PutProjectsIDRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PutProjectsIDRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PutProjectsIDRequest) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PutProjectsIDRequest) GetBody() *PutProjectsIDRequestBody {
	if p == nil {
		return nil
	}
	return p.Body
}

// PutProjectsIDResponseBody - A single project
type PutProjectsIDResponseBody struct {
	// A unique numeric identifier for the project within the system.
	ID int64 `json:"id"`
	// The project’s display name.
	Name string `json:"name"`
	// The project’s description.
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	// The number of different medias that have been uploaded to the project.
	MediaCount int64 `json:"mediaCount"`
	// The date that the project was originally created.
	Created time.Time `json:"created"`
	// The date that the project was last updated.
	Updated time.Time `json:"updated"`
	// A private hashed id, uniquely identifying the project within the system.
	HashedID string `json:"hashedId"`
	// A boolean indicating whether the project is available for public (anonymous) viewing.
	Public bool `json:"public"`
	// If the project is public, this field contains a string representing the ID used for referencing the project in public URLs.
	PublicID             *string `json:"publicId"`
	AnonymousCanUpload   *bool   `json:"anonymousCanUpload,omitzero"`
	AnonymousCanDownload *bool   `json:"anonymousCanDownload,omitzero"`
}

func (p PutProjectsIDResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PutProjectsIDResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PutProjectsIDResponseBody) GetID() int64 {
	if p == nil {
		return 0
	}
	return p.ID
}

func (p *PutProjectsIDResponseBody) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PutProjectsIDResponseBody) GetDescription() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *PutProjectsIDResponseBody) GetMediaCount() int64 {
	if p == nil {
		return 0
	}
	return p.MediaCount
}

func (p *PutProjectsIDResponseBody) GetCreated() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.Created
}

func (p *PutProjectsIDResponseBody) GetUpdated() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.Updated
}

func (p *PutProjectsIDResponseBody) GetHashedID() string {
	if p == nil {
		return ""
	}
	return p.HashedID
}

func (p *PutProjectsIDResponseBody) GetPublic() bool {
	if p == nil {
		return false
	}
	return p.Public
}

func (p *PutProjectsIDResponseBody) GetPublicID() *string {
	if p == nil {
		return nil
	}
	return p.PublicID
}

func (p *PutProjectsIDResponseBody) GetAnonymousCanUpload() *bool {
	if p == nil {
		return nil
	}
	return p.AnonymousCanUpload
}

func (p *PutProjectsIDResponseBody) GetAnonymousCanDownload() *bool {
	if p == nil {
		return nil
	}
	return p.AnonymousCanDownload
}

type PutProjectsIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A single project
	Object *PutProjectsIDResponseBody
}

func (p PutProjectsIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PutProjectsIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PutProjectsIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PutProjectsIDResponse) GetObject() *PutProjectsIDResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
