// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f71557debfb5

package sdkerrors

import (
	"encoding/json"
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
)

// DeleteChannelEpisodesChannelEpisodeHashedIDInternalServerError - Internal server error
type DeleteChannelEpisodesChannelEpisodeHashedIDInternalServerError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &DeleteChannelEpisodesChannelEpisodeHashedIDInternalServerError{}

func (e *DeleteChannelEpisodesChannelEpisodeHashedIDInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// DeleteChannelEpisodesChannelEpisodeHashedIDForbiddenError - Forbidden, token is valid but account does not have access to feature
type DeleteChannelEpisodesChannelEpisodeHashedIDForbiddenError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &DeleteChannelEpisodesChannelEpisodeHashedIDForbiddenError{}

func (e *DeleteChannelEpisodesChannelEpisodeHashedIDForbiddenError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// DeleteChannelEpisodesChannelEpisodeHashedIDUnauthorizedError - Unauthorized, invalid or missing token
type DeleteChannelEpisodesChannelEpisodeHashedIDUnauthorizedError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &DeleteChannelEpisodesChannelEpisodeHashedIDUnauthorizedError{}

func (e *DeleteChannelEpisodesChannelEpisodeHashedIDUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
