// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 446e1e35b626

package sdkerrors

import (
	"encoding/json"
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
	"github.com/wistia/wistia-cli/internal/sdk/models/operations"
)

// GetAccountDetailsInternalServerError - Internal server error
type GetAccountDetailsInternalServerError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetAccountDetailsInternalServerError{}

func (e *GetAccountDetailsInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetAccountDetailsUnauthorizedError - Unauthorized, invalid or missing token
type GetAccountDetailsUnauthorizedError struct {
	// A machine-readable identifier for the specific authorization failure.
	Code     *operations.GetAccountDetailsCode `json:"code,omitzero"`
	Error_   *string                           `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata           `json:"-"`
}

var _ error = &GetAccountDetailsUnauthorizedError{}

func (e *GetAccountDetailsUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
