// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9eaba995ebde

package sdkerrors

import (
	"encoding/json"
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
)

// GetAnalyticsMediasMediaIDTrafficServiceUnavailableError - Analytics service is temporarily unavailable
type GetAnalyticsMediasMediaIDTrafficServiceUnavailableError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetAnalyticsMediasMediaIDTrafficServiceUnavailableError{}

func (e *GetAnalyticsMediasMediaIDTrafficServiceUnavailableError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetAnalyticsMediasMediaIDTrafficInternalServerError - Internal server error
type GetAnalyticsMediasMediaIDTrafficInternalServerError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetAnalyticsMediasMediaIDTrafficInternalServerError{}

func (e *GetAnalyticsMediasMediaIDTrafficInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetAnalyticsMediasMediaIDTrafficForbiddenError - Forbidden, token is valid but account does not have access to feature
type GetAnalyticsMediasMediaIDTrafficForbiddenError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetAnalyticsMediasMediaIDTrafficForbiddenError{}

func (e *GetAnalyticsMediasMediaIDTrafficForbiddenError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetAnalyticsMediasMediaIDTrafficUnauthorizedError - Unauthorized, invalid or missing token
type GetAnalyticsMediasMediaIDTrafficUnauthorizedError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetAnalyticsMediasMediaIDTrafficUnauthorizedError{}

func (e *GetAnalyticsMediasMediaIDTrafficUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetAnalyticsMediasMediaIDTrafficBadRequestError - Bad request
type GetAnalyticsMediasMediaIDTrafficBadRequestError struct {
	// Error message detailing the reason for the bad request.
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetAnalyticsMediasMediaIDTrafficBadRequestError{}

func (e *GetAnalyticsMediasMediaIDTrafficBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
