// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
)

// GetChannelsChannelHashedIDChannelEpisodesChannelEpisodeIDInternalServerError - Internal server error
type GetChannelsChannelHashedIDChannelEpisodesChannelEpisodeIDInternalServerError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetChannelsChannelHashedIDChannelEpisodesChannelEpisodeIDInternalServerError{}

func (e *GetChannelsChannelHashedIDChannelEpisodesChannelEpisodeIDInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetChannelsChannelHashedIDChannelEpisodesChannelEpisodeIDUnauthorizedError - Unauthorized, invalid or missing token
type GetChannelsChannelHashedIDChannelEpisodesChannelEpisodeIDUnauthorizedError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetChannelsChannelHashedIDChannelEpisodesChannelEpisodeIDUnauthorizedError{}

func (e *GetChannelsChannelHashedIDChannelEpisodesChannelEpisodeIDUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
