// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 89e703b66020

package sdkerrors

import (
	"encoding/json"
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
)

// GetMediaExtendedAudioDescriptionsInternalServerError - Internal server error
type GetMediaExtendedAudioDescriptionsInternalServerError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetMediaExtendedAudioDescriptionsInternalServerError{}

func (e *GetMediaExtendedAudioDescriptionsInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetMediaExtendedAudioDescriptionsUnauthorizedError - Unauthorized, invalid or missing token
type GetMediaExtendedAudioDescriptionsUnauthorizedError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetMediaExtendedAudioDescriptionsUnauthorizedError{}

func (e *GetMediaExtendedAudioDescriptionsUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
