// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: adbe0e10429d

package sdkerrors

import (
	"encoding/json"
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
)

// GetProjectsInternalServerError - Internal server error
type GetProjectsInternalServerError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetProjectsInternalServerError{}

func (e *GetProjectsInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetProjectsUnauthorizedError - Unauthorized, invalid or missing token
type GetProjectsUnauthorizedError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetProjectsUnauthorizedError{}

func (e *GetProjectsUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
