// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 292abb6c86b4

package sdkerrors

import (
	"encoding/json"
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
)

// GetProjectsProjectIDSharingsInternalServerError - Internal server error
type GetProjectsProjectIDSharingsInternalServerError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetProjectsProjectIDSharingsInternalServerError{}

func (e *GetProjectsProjectIDSharingsInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetProjectsProjectIDSharingsUnauthorizedError - Unauthorized, invalid or missing token
type GetProjectsProjectIDSharingsUnauthorizedError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetProjectsProjectIDSharingsUnauthorizedError{}

func (e *GetProjectsProjectIDSharingsUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
