// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0b14f3b2f555

package sdkerrors

import (
	"encoding/json"
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
	"github.com/wistia/wistia-cli/internal/sdk/models/operations"
)

// PostFormBadRequestError - Error due to reaching the video limit of your account or other issues.
type PostFormBadRequestError struct {
	Error_   *operations.PostFormError `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata   `json:"-"`
}

var _ error = &PostFormBadRequestError{}

func (e *PostFormBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
