// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: dae2973a8b84

package sdkerrors

import (
	"encoding/json"
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
	"github.com/wistia/wistia-cli/internal/sdk/models/operations"
)

// PostRemixesRemixHashedIDExportInternalServerError - Internal server error
type PostRemixesRemixHashedIDExportInternalServerError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &PostRemixesRemixHashedIDExportInternalServerError{}

func (e *PostRemixesRemixHashedIDExportInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// PostRemixesRemixHashedIDExportUnprocessableEntityError - Unprocessable entity (e.g., remix not ready for export).
type PostRemixesRemixHashedIDExportUnprocessableEntityError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &PostRemixesRemixHashedIDExportUnprocessableEntityError{}

func (e *PostRemixesRemixHashedIDExportUnprocessableEntityError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// PostRemixesRemixHashedIDExportNotFoundError - Resource not found
type PostRemixesRemixHashedIDExportNotFoundError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &PostRemixesRemixHashedIDExportNotFoundError{}

func (e *PostRemixesRemixHashedIDExportNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// PostRemixesRemixHashedIDExportUnauthorizedError - Unauthorized, invalid or missing token
type PostRemixesRemixHashedIDExportUnauthorizedError struct {
	// A machine-readable identifier for the specific authorization failure.
	Code     *operations.PostRemixesRemixHashedIDExportCode `json:"code,omitzero"`
	Error_   *string                                        `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata                        `json:"-"`
}

var _ error = &PostRemixesRemixHashedIDExportUnauthorizedError{}

func (e *PostRemixesRemixHashedIDExportUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
