// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1ac51a47b226

package sdkerrors

import (
	"encoding/json"
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
	"github.com/wistia/wistia-cli/internal/sdk/models/operations"
)

// PutFoldersFolderIDSubfoldersSubfolderIDInternalServerError - Internal server error
type PutFoldersFolderIDSubfoldersSubfolderIDInternalServerError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &PutFoldersFolderIDSubfoldersSubfolderIDInternalServerError{}

func (e *PutFoldersFolderIDSubfoldersSubfolderIDInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// PutFoldersFolderIDSubfoldersSubfolderIDNotFoundError - Folder or subfolder not found
type PutFoldersFolderIDSubfoldersSubfolderIDNotFoundError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &PutFoldersFolderIDSubfoldersSubfolderIDNotFoundError{}

func (e *PutFoldersFolderIDSubfoldersSubfolderIDNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// PutFoldersFolderIDSubfoldersSubfolderIDUnauthorizedError - Unauthorized, invalid or missing token
type PutFoldersFolderIDSubfoldersSubfolderIDUnauthorizedError struct {
	// A machine-readable identifier for the specific authorization failure.
	Code     *operations.PutFoldersFolderIDSubfoldersSubfolderIDCode `json:"code,omitzero"`
	Error_   *string                                                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata                                 `json:"-"`
}

var _ error = &PutFoldersFolderIDSubfoldersSubfolderIDUnauthorizedError{}

func (e *PutFoldersFolderIDSubfoldersSubfolderIDUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
