// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4f08966b7f84

package sdkerrors

import (
	"encoding/json"
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
	"github.com/wistia/wistia-cli/internal/sdk/models/operations"
)

// PutMediasMediaIDCustomizationsAccessInternalServerError - Internal server error
type PutMediasMediaIDCustomizationsAccessInternalServerError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &PutMediasMediaIDCustomizationsAccessInternalServerError{}

func (e *PutMediasMediaIDCustomizationsAccessInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// PutMediasMediaIDCustomizationsAccessNotFoundError - Resource not found
type PutMediasMediaIDCustomizationsAccessNotFoundError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &PutMediasMediaIDCustomizationsAccessNotFoundError{}

func (e *PutMediasMediaIDCustomizationsAccessNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// PutMediasMediaIDCustomizationsAccessForbiddenError - Forbidden, token is valid but account does not have access to feature
type PutMediasMediaIDCustomizationsAccessForbiddenError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &PutMediasMediaIDCustomizationsAccessForbiddenError{}

func (e *PutMediasMediaIDCustomizationsAccessForbiddenError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// PutMediasMediaIDCustomizationsAccessUnauthorizedError - Unauthorized, invalid or missing token
type PutMediasMediaIDCustomizationsAccessUnauthorizedError struct {
	// A machine-readable identifier for the specific authorization failure.
	Code     *operations.PutMediasMediaIDCustomizationsAccessCode `json:"code,omitzero"`
	Error_   *string                                              `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata                              `json:"-"`
}

var _ error = &PutMediasMediaIDCustomizationsAccessUnauthorizedError{}

func (e *PutMediasMediaIDCustomizationsAccessUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// PutMediasMediaIDCustomizationsAccessBadRequestError - Bad request
type PutMediasMediaIDCustomizationsAccessBadRequestError struct {
	// Error message detailing the reason for the bad request.
	Error_ *string `json:"error,omitzero"`
	// Array of error messages detailing the reasons for the bad request.
	Errors   []string                `json:"errors,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &PutMediasMediaIDCustomizationsAccessBadRequestError{}

func (e *PutMediasMediaIDCustomizationsAccessBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
