// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 36b6afd5449a

package sdkerrors

import (
	"encoding/json"
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
	"github.com/wistia/wistia-cli/internal/sdk/models/operations"
)

// PutMediasMediaIDCustomizationsLeadCaptureInternalServerError - Internal server error
type PutMediasMediaIDCustomizationsLeadCaptureInternalServerError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &PutMediasMediaIDCustomizationsLeadCaptureInternalServerError{}

func (e *PutMediasMediaIDCustomizationsLeadCaptureInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// PutMediasMediaIDCustomizationsLeadCaptureNotFoundError - Resource not found
type PutMediasMediaIDCustomizationsLeadCaptureNotFoundError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &PutMediasMediaIDCustomizationsLeadCaptureNotFoundError{}

func (e *PutMediasMediaIDCustomizationsLeadCaptureNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// PutMediasMediaIDCustomizationsLeadCaptureForbiddenError - Forbidden, token is valid but account does not have access to feature
type PutMediasMediaIDCustomizationsLeadCaptureForbiddenError struct {
	Error_   *string                 `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &PutMediasMediaIDCustomizationsLeadCaptureForbiddenError{}

func (e *PutMediasMediaIDCustomizationsLeadCaptureForbiddenError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// PutMediasMediaIDCustomizationsLeadCaptureUnauthorizedError - Unauthorized, invalid or missing token
type PutMediasMediaIDCustomizationsLeadCaptureUnauthorizedError struct {
	// A machine-readable identifier for the specific authorization failure.
	Code     *operations.PutMediasMediaIDCustomizationsLeadCaptureCode `json:"code,omitzero"`
	Error_   *string                                                   `json:"error,omitzero"`
	HTTPMeta components.HTTPMetadata                                   `json:"-"`
}

var _ error = &PutMediasMediaIDCustomizationsLeadCaptureUnauthorizedError{}

func (e *PutMediasMediaIDCustomizationsLeadCaptureUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// PutMediasMediaIDCustomizationsLeadCaptureBadRequestError - Bad request
type PutMediasMediaIDCustomizationsLeadCaptureBadRequestError struct {
	// Error message detailing the reason for the bad request.
	Error_ *string `json:"error,omitzero"`
	// Array of error messages detailing the reasons for the bad request.
	Errors   []string                `json:"errors,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &PutMediasMediaIDCustomizationsLeadCaptureBadRequestError{}

func (e *PutMediasMediaIDCustomizationsLeadCaptureBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
