// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 999e4d5191e1

package customizations

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/wistia/wistia-cli/internal/client"
	"github.com/wistia/wistia-cli/internal/flagutil"
	"github.com/wistia/wistia-cli/internal/interactive"
	"github.com/wistia/wistia-cli/internal/output"
	"github.com/wistia/wistia-cli/internal/sdk"
	"github.com/wistia/wistia-cli/internal/sdk/models/operations"
	"github.com/wistia/wistia-cli/internal/usage"
)

var getAccessibilityCmdMeta = []flagutil.FlagMeta{
	{FlagName: "media-id", Shorthand: "m", FieldPath: "MediaID", Kind: flagutil.FlagKindString, Required: true, Description: "The hashed ID of the video. [required]"},
}

// initGetAccessibilityCmd initializes the get-accessibility command.
func initGetAccessibilityCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-accessibility",
		Short:   "Show Accessibility Customizations",
		Long:    "Fetches the explicitly-set accessibility customizations (caption display and\nstyling, transcript display, and audio description) for the video.\n\n## Requires api token with one of the following permissions\n```\nRead all folder and media data\n```\n\nTokens with the \"Act with a team member's permissions\" permission\n(`all:delegate_to_contact_permissions` scope) can also be used. Requests\nmade with such a token are authorized using the permissions of the\ncontact assigned to the token.",
		Example: "  wistia customizations get-accessibility --media-id <id>",
		RunE:    runGetAccessibilityCmd,
		Aliases: []string{"gac"},
	}
	flagutil.RegisterFlags(cmd, getAccessibilityCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetMediasMediaIDCustomizationsAccessibilityRequest](getAccessibilityCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-accessibility: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetAccessibilityCmd executes the get-accessibility command.
func runGetAccessibilityCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getAccessibilityCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getAccessibilityCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetMediasMediaIDCustomizationsAccessibilityRequest](cmd, getAccessibilityCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Customizations.GetAccessibility(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
