// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c5a60951d29c

package customizations

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/wistia/wistia-cli/internal/client"
	"github.com/wistia/wistia-cli/internal/flagutil"
	"github.com/wistia/wistia-cli/internal/interactive"
	"github.com/wistia/wistia-cli/internal/output"
	"github.com/wistia/wistia-cli/internal/sdk"
	"github.com/wistia/wistia-cli/internal/sdk/models/operations"
	"github.com/wistia/wistia-cli/internal/usage"
)

var updateThumbnailCmdMeta = []flagutil.FlagMeta{
	{FlagName: "media-id", Shorthand: "m", FieldPath: "MediaID", Kind: flagutil.FlagKindString, Required: true, Description: "The hashed ID of the video to be customized. [required]"},
	{FlagName: "still-url", Shorthand: "s", FieldPath: "Body.StillURL", Kind: flagutil.FlagKindString, Optional: true, Description: "Overrides the thumbnail image that appears before the video plays."},
	{FlagName: "thumbnail-alt-text", Shorthand: "t", FieldPath: "Body.ThumbnailAltText", Kind: flagutil.FlagKindString, Optional: true, Description: "Alt text for the thumbnail image, used for accessibility."},
	{FlagName: "fit-strategy", Shorthand: "f", FieldPath: "Body.FitStrategy", Kind: flagutil.FlagKindString, Optional: true, Description: "Resizes the thumbnail when there's a discrepancy between its aspect ratio and that of its parent container. Options are contain, cover, fill, and none."},
	{FlagName: "unaltered-still-image-asset", Shorthand: "u", FieldPath: "Body.UnalteredStillImageAsset", Kind: flagutil.FlagKindString, Optional: true, Description: "Reference to the original, unaltered still image asset."},
	{FlagName: "plugin", Shorthand: "p", FieldPath: "Body.Plugin", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"plugin,omitempty"`, Description: "Container for thumbnail-related player plugin configurations."},
}

// initUpdateThumbnailCmd initializes the update-thumbnail command.
func initUpdateThumbnailCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "update-thumbnail",
		Short:   "Update Thumbnail Customizations",
		Long:    "Applies a partial update to a video's thumbnail customizations. Only the\nfields supplied are changed; sending a field as null deletes it (reverting to\nthe default).\n\n## Requires api token with one of the following permissions\n```\nRead, update & delete anything\n```\n\nTokens with the \"Act with a team member's permissions\" permission\n(`all:delegate_to_contact_permissions` scope) can also be used. Requests\nmade with such a token are authorized using the permissions of the\ncontact assigned to the token.",
		Example: "  wistia customizations update-thumbnail --media-id <id>",
		RunE:    runUpdateThumbnailCmd,
		Aliases: []string{"ut"},
	}
	flagutil.RegisterFlags(cmd, updateThumbnailCmdMeta)
	if err := flagutil.ValidateMeta[operations.PutMediasMediaIDCustomizationsThumbnailRequest](updateThumbnailCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for update-thumbnail: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runUpdateThumbnailCmd executes the update-thumbnail command.
func runUpdateThumbnailCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, updateThumbnailCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, updateThumbnailCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PutMediasMediaIDCustomizationsThumbnailRequest](cmd, updateThumbnailCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Customizations.UpdateThumbnail(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
