// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 895a2f33b0a3

package folders

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/wistia/wistia-cli/internal/client"
	"github.com/wistia/wistia-cli/internal/flagutil"
	"github.com/wistia/wistia-cli/internal/output"
	"github.com/wistia/wistia-cli/internal/sdk"
	"github.com/wistia/wistia-cli/internal/sdk/models/operations"
	"github.com/wistia/wistia-cli/internal/usage"
)

var listCmdMeta = []flagutil.FlagMeta{
	{FlagName: "page", FieldPath: "Page", Kind: flagutil.FlagKindInt64, Optional: true, Description: "The page number to retrieve. This cannot be combined with 'cursor',\npagination."},
	{FlagName: "per-page", FieldPath: "PerPage", Kind: flagutil.FlagKindInt64, Optional: true, Description: "The number of medias per page. Use this for both offset pagination and cursor pagination."},
	{FlagName: "cursor", Shorthand: "c", FieldPath: "Cursor", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `queryParam:"style=deepObject,explode=true,name=cursor"`, Description: "If 'cursor[enabled]' is set to 1 then cursor pagination is enabled and the\nfirst set of records are fetched up to the 'per_page'. Cursor\npagination will also be turned on if 'cursor[before]' or 'cursor[after]'\nare set. Records returned will have a 'cursor' property set which can be used to fetch more records in the same 'sort_by' ordering.\nThe cursor value of the last record can be used to fetch records after the current result set and\nthe cursor of the first record can be used to fetch records before the result set.\n\nNOTE: a cursor value is only valid if the 'sort_by' value hasn't changed from the\nlast fetch. For example, you cannot fetch using 'sort_by' id and then pass that\ncursor value to a 'sort_by' name."},
	{FlagName: "sort-by", FieldPath: "SortBy", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"name", "created", "updated", "mediaCount", "id"}, Description: "Ordering. When using cursor pagination (see cursor param),\nonly 'id', 'updated' and 'created' are supported. All other sort_by options\nrequire offset pagination.\n(options: name, created, updated, mediaCount, id)"},
	{FlagName: "sort-direction", FieldPath: "SortDirection", Kind: flagutil.FlagKindIntEnum, Optional: true, EnumValues: []string{"0", "1"}, Description: "Ordering Sort Direction (0 = desc, 1 = asc; default is 1) (options: 0, 1)"},
	{FlagName: "hashed-ids", FieldPath: "HashedIds", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "A collection of hashed ids belonging to folders to fetch"},
}

// initListCmd initializes the list command.
func initListCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list",
		Short:   "List Folders",
		Long:    "Lists folders (previously called projects) belonging to the account.\nMy Library folders are not included.\n\nFor tokens scoped to a specific user (`all:delegate_to_contact_permissions`),\nresults are limited to folders that user can see in their content library:\nfolders shared with them directly, through a contact group, or with the\nwhole account (owners and managers see every folder). Public (unlocked)\nfolders the user has no sharing on remain viewable by link but are not\nlisted.\n\n## Requires api token with one of the following permissions\n```\nRead all folder and media data\n```\n\nTokens with the \"Act with a team member's permissions\" permission\n(`all:delegate_to_contact_permissions` scope) can also be used. Requests\nmade with such a token are authorized using the permissions of the\ncontact assigned to the token.\n\nAn [expiring access token](https://docs.wistia.com/reference/post_expiring-token)\ncreated with the `all:delegate_to_contact_permissions` scope can also be\nused. Results are limited to the folders its authorizations name (any\npermission granted on a folder qualifies it), filtered as they would be\nfor the contact the token was created for.",
		Example: "  wistia folders list",
		Args:    cobra.NoArgs,
		RunE:    runListCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "get_/folders",
		},
	}
	flagutil.RegisterFlags(cmd, listCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetFoldersRequest](listCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListCmd executes the list command.
func runListCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	req, err := flagutil.BuildRequest[operations.GetFoldersRequest](cmd, listCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Folders.List(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
