// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 52e0f162a096

package subfolders

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/wistia/wistia-cli/internal/client"
	"github.com/wistia/wistia-cli/internal/flagutil"
	"github.com/wistia/wistia-cli/internal/interactive"
	"github.com/wistia/wistia-cli/internal/output"
	"github.com/wistia/wistia-cli/internal/sdk"
	"github.com/wistia/wistia-cli/internal/sdk/models/operations"
	"github.com/wistia/wistia-cli/internal/usage"
)

var getFoldersFolderIDSubfoldersSubfolderIDCmdMeta = []flagutil.FlagMeta{
	{FlagName: "folder-id", Shorthand: "f", FieldPath: "FolderID", Kind: flagutil.FlagKindString, Required: true, Description: "The hashed ID of the folder [required]"},
	{FlagName: "subfolder-id", Shorthand: "s", FieldPath: "SubfolderID", Kind: flagutil.FlagKindString, Required: true, Description: "The hashed ID of the subfolder [required]"},
}

// initGetFoldersFolderIdSubfoldersSubfolderIdCmd initializes the get-folders-folder-id-subfolders-subfolder-id command.
func initGetFoldersFolderIdSubfoldersSubfolderIdCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-folders-folder-id-subfolders-subfolder-id",
		Short:   "Show Subfolder",
		Long:    "Retrieves detailed information about a specific subfolder, including all media contained within it.\n\n## Requires api token with one of the following permissions\n```\nRead all folder and media data\n```",
		Example: "  wistia subfolders get-folders-folder-id-subfolders-subfolder-id --folder-id abc123def4 --subfolder-id xyz789ghi0",
		RunE:    runGetFoldersFolderIdSubfoldersSubfolderIdCmd,
		Aliases: []string{"gffissi"},
	}
	flagutil.RegisterFlags(cmd, getFoldersFolderIDSubfoldersSubfolderIDCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetFoldersFolderIDSubfoldersSubfolderIDRequest](getFoldersFolderIDSubfoldersSubfolderIDCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-folders-folder-id-subfolders-subfolder-id: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetFoldersFolderIdSubfoldersSubfolderIdCmd executes the get-folders-folder-id-subfolders-subfolder-id command.
func runGetFoldersFolderIdSubfoldersSubfolderIdCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getFoldersFolderIDSubfoldersSubfolderIDCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getFoldersFolderIDSubfoldersSubfolderIDCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetFoldersFolderIDSubfoldersSubfolderIDRequest](cmd, getFoldersFolderIDSubfoldersSubfolderIDCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Subfolders.GetFoldersFolderIDSubfoldersSubfolderID(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
