// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d541f71c7f20

package remix

import (
	"github.com/spf13/cobra"
	"github.com/wistia/wistia-cli/internal/client"
	"github.com/wistia/wistia-cli/internal/output"
	"github.com/wistia/wistia-cli/internal/sdk"
	"github.com/wistia/wistia-cli/internal/sdk/models/operations"
	"github.com/wistia/wistia-cli/internal/usage"
)

// initGetRemixAccountStatusCmd initializes the get-remix-account-status command.
func initGetRemixAccountStatusCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-remix-account-status",
		Short:   "Get Remix Account Status",
		Long:    "Check the current account's Remix billing mode and ability to create a Remix.\n\n\n## Requires api token with one of the following permissions\n```\nRead all folder and media data\n```\n\nTokens with the \"Act with a team member's permissions\" permission\n(`all:delegate_to_contact_permissions` scope) can also be used. Requests\nmade with such a token are authorized using the permissions of the\ncontact assigned to the token.",
		Example: "  wistia remix get-remix-account-status",
		Args:    cobra.NoArgs,
		RunE:    runGetRemixAccountStatusCmd,
		Aliases: []string{"gras"},
		Annotations: map[string]string{
			"speakeasy_operation": "get_/remix_account_status",
		},
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetRemixAccountStatusCmd executes the get-remix-account-status command.
func runGetRemixAccountStatusCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	stopProgress := output.StartRequestProgress(cmd)
	defer stopProgress()
	res, err := s.Remix.GetRemixAccountStatus(cmd.Context(), sdkOpts...)
	stopProgress()
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
