// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c16eb0035c4f

package resourceurls

import (
	"github.com/spf13/cobra"
	"github.com/wistia/wistia-cli/internal/usage"
)

func InitResourceUrlsRoot(parent *cobra.Command) error {
	var ResourceUrlsCmd = &cobra.Command{
		Use:         "resource-urls",
		Short:       "Operations for resource-urls",
		Long:        "Operations for resource-urls",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"speakeasy_cli_group": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
		Aliases: []string{"ru"},
	}

	if err := initResolveCmd(ResourceUrlsCmd); err != nil {
		return err
	}

	parent.AddCommand(ResourceUrlsCmd)
	return nil
}
