// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5898305eedad

package client

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/wistia/wistia-cli/internal/config"
	"github.com/wistia/wistia-cli/internal/flagutil"
	"github.com/wistia/wistia-cli/internal/sdk"
	"github.com/wistia/wistia-cli/internal/sdk/models/components"
	"github.com/wistia/wistia-cli/internal/testclient"
	"net/http"
	"strconv"
	"time"
)

// NewClient creates a new SDK client configured from command flags and environment.
// It handles global security, server URL/selection override, global parameters,
// retry configuration, timeout, and test client injection.
func NewClient(cmd *cobra.Command) (*sdk.Wistia, error) {
	var sdkOpts []sdk.SDKOption
	sdkOpts = append(sdkOpts, sdk.WithSecurity(buildGlobalSecurity(cmd)))
	if serverURL, _ := flagutil.GetStringFlag(cmd, "server-url"); serverURL != "" {
		sdkOpts = append(sdkOpts, sdk.WithServerURL(serverURL))
	} else if serverFlag, _ := flagutil.GetStringFlag(cmd, "server"); serverFlag != "" {
		// Silently skip non-integer or out-of-range values — they may be intended for operation-level servers.
		if idx, err := strconv.Atoi(serverFlag); err == nil && idx >= 0 && idx < len(sdk.ServerList) {
			sdkOpts = append(sdkOpts, sdk.WithServerIndex(idx))
		}
	}

	// Timeout (always available)
	if timeoutStr := resolveStringFlag(cmd, "timeout"); timeoutStr != "" {
		timeout, err := time.ParseDuration(timeoutStr)
		if err != nil {
			return nil, fmt.Errorf("invalid --timeout value %q: %w", timeoutStr, err)
		}
		sdkOpts = append(sdkOpts, sdk.WithTimeout(timeout))
	}

	// Diagnostics and test client composition.
	// Order: test client (innermost) → diagnostics wrapper (outermost).
	var httpClient HTTPClient = &http.Client{}
	if testClient := testclient.NewTestHTTPClient(); testClient != nil {
		httpClient = testClient
	}
	httpClient = WrapClientForDiagnostics(cmd, httpClient)
	sdkOpts = append(sdkOpts, sdk.WithClient(httpClient))
	return sdk.New(sdkOpts...), nil
}

// resolveStringFlag reads a string flag with priority: flag > env > config.
func resolveStringFlag(cmd *cobra.Command, name string) string {
	if val, changed := flagutil.GetStringFlag(cmd, name); changed && val != "" {
		return val
	}
	return config.GetString(name)
}

// buildGlobalSecurity reads security credentials from flags, env vars, and config file.
// Priority: flag > env var > config file.
func buildGlobalSecurity(cmd *cobra.Command) components.Security {
	// Resolve security credentials: flag > env var > keyring > config file
	bearerAuth, _ := config.ResolveSecurityCredential(cmd, "bearer-auth")
	globalSecurity := components.Security{}
	if bearerAuth != "" {
		globalSecurity.BearerAuth = bearerAuth
	}
	return globalSecurity
}
