// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 207e15b79ff7

package analyticswebinar

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/wistia/wistia-cli/internal/client"
	"github.com/wistia/wistia-cli/internal/flagutil"
	"github.com/wistia/wistia-cli/internal/interactive"
	"github.com/wistia/wistia-cli/internal/output"
	"github.com/wistia/wistia-cli/internal/sdk"
	"github.com/wistia/wistia-cli/internal/sdk/models/operations"
	"github.com/wistia/wistia-cli/internal/usage"
)

var getAnalyticsWebinarsWebinarIDHistogramsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "webinar-id", Shorthand: "w", FieldPath: "WebinarID", Kind: flagutil.FlagKindString, Required: true, Description: "The hashed ID of the webinar. [required]"},
}

// initGetAnalyticsWebinarsWebinarIdHistogramsCmd initializes the get-analytics-webinars-webinar-id-histograms command.
func initGetAnalyticsWebinarsWebinarIdHistogramsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-analytics-webinars-webinar-id-histograms",
		Short:   "Show Webinar Histograms",
		Long:    "Retrieve engagement histogram data for a webinar. Returns arrays of\nper-time-bucket counts for attendees, chat activity, and visual focus,\nuseful for rendering engagement visualizations.\n\n<!--- HIDE-MCP -->\n## Requires api token with one of the following permissions\n```\nRead detailed stats\n```\n<!--- /HIDE-MCP -->",
		Example: "  wistia analytics-webinar get-analytics-webinars-webinar-id-histograms --webinar-id <id>",
		RunE:    runGetAnalyticsWebinarsWebinarIdHistogramsCmd,
		Aliases: []string{"gawwih"},
	}
	flagutil.RegisterFlags(cmd, getAnalyticsWebinarsWebinarIDHistogramsCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetAnalyticsWebinarsWebinarIDHistogramsRequest](getAnalyticsWebinarsWebinarIDHistogramsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-analytics-webinars-webinar-id-histograms: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetAnalyticsWebinarsWebinarIdHistogramsCmd executes the get-analytics-webinars-webinar-id-histograms command.
func runGetAnalyticsWebinarsWebinarIdHistogramsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getAnalyticsWebinarsWebinarIDHistogramsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getAnalyticsWebinarsWebinarIDHistogramsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetAnalyticsWebinarsWebinarIDHistogramsRequest](cmd, getAnalyticsWebinarsWebinarIDHistogramsCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.AnalyticsWebinar.GetAnalyticsWebinarsWebinarIDHistograms(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
