// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 79fe863a6a42

package analyticswebinar

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/wistia/wistia-cli/internal/client"
	"github.com/wistia/wistia-cli/internal/flagutil"
	"github.com/wistia/wistia-cli/internal/interactive"
	"github.com/wistia/wistia-cli/internal/output"
	"github.com/wistia/wistia-cli/internal/sdk"
	"github.com/wistia/wistia-cli/internal/sdk/models/operations"
	"github.com/wistia/wistia-cli/internal/usage"
)

var getRegistrationCmdMeta = []flagutil.FlagMeta{
	{FlagName: "webinar-id", Shorthand: "w", FieldPath: "WebinarID", Kind: flagutil.FlagKindString, Required: true, Description: "The hashed ID of the webinar. [required]"},
	{FlagName: "granularity", Shorthand: "g", FieldPath: "Granularity", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"daily", "weekly", "monthly"}, Description: "The time granularity for the timeseries data. (options: daily, weekly, monthly) [required]"},
	{FlagName: "include-post-event", Shorthand: "i", FieldPath: "IncludePostEvent", Kind: flagutil.FlagKindBool, Optional: true, HasDefault: true, Description: "Whether to include on-demand viewing data after the live event ended."},
	{FlagName: "post-event-start-date", FieldPath: "PostEventStartDate", Kind: flagutil.FlagKindDate, Optional: true, Description: "Start date for the post-event analytics period in ISO 8601 format (YYYY-MM-DD). Inclusive — the range starts at the beginning of this date. Defaults to the date the event ended. Only used when include_post_event is true."},
	{FlagName: "post-event-end-date", FieldPath: "PostEventEndDate", Kind: flagutil.FlagKindDate, Optional: true, Description: "End date for the post-event analytics period in ISO 8601 format (YYYY-MM-DD). Exclusive — the range ends before the beginning of this date. Defaults to tomorrow, so the range runs through today. Only used when include_post_event is true."},
}

// initGetRegistrationCmd initializes the get-registration command.
func initGetRegistrationCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-registration [webinar-id]",
		Short:   "Show Webinar Registration Timeseries",
		Long:    "Retrieve registration timeseries data for a webinar with configurable\ngranularity. Returns an array of timestamped registration metric buckets\nincluding impressions, registrations, and completion rates.\n\n\n## Requires api token with one of the following permissions\n```\nRead detailed stats\n```\n\nTokens with the \"Act with a team member's permissions\" permission\n(`all:delegate_to_contact_permissions` scope) can also be used. Requests\nmade with such a token are authorized using the permissions of the\ncontact assigned to the token.\n\nAn [expiring access token](https://docs.wistia.com/reference/post_expiring-token)\ncreated with the `all:delegate_to_contact_permissions` scope and an\nauthorization granting the `view-stats` permission on this webinar can also\nbe used.",
		Example: "  wistia analytics-webinar get-registration --webinar-id <id> --granularity monthly",
		Args:    flagutil.PositionalFlagArgs,
		RunE:    runGetRegistrationCmd,
		Aliases: []string{"gr"},
		Annotations: map[string]string{
			"speakeasy_operation": "get_/analytics/webinars/{webinarId}/registration",
		},
	}
	flagutil.RegisterFlags(cmd, getRegistrationCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetAnalyticsWebinarsWebinarIDRegistrationRequest](getRegistrationCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-registration: %w", err)
	}
	if err := flagutil.DeclarePositionalFlag(cmd, "webinar-id", "The hashed ID of the webinar. (or pass it as the [webinar-id] argument)", true); err != nil {
		return err
	}
	if err := interactive.Declare(cmd, interactive.CommandSpec{Args: []interactive.ArgSpec{
		{Name: "webinar-id", Summary: "The hashed ID of the webinar.", Required: true, SatisfiedBy: []string{"webinar-id"}},
	}}); err != nil {
		return fmt.Errorf("declare interactive arguments for get-registration: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetRegistrationCmd executes the get-registration command.
func runGetRegistrationCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if err := flagutil.ResolvePositionalFlag(cmd, args); err != nil {
		return err
	}
	req, err := flagutil.BuildRequest[operations.GetAnalyticsWebinarsWebinarIDRegistrationRequest](cmd, getRegistrationCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	stopProgress := output.StartRequestProgress(cmd)
	defer stopProgress()
	res, err := s.AnalyticsWebinar.GetRegistration(cmd.Context(), *req, sdkOpts...)
	stopProgress()
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
