// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0d28f345c644

package brands

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/wistia/wistia-cli/internal/client"
	"github.com/wistia/wistia-cli/internal/flagutil"
	"github.com/wistia/wistia-cli/internal/interactive"
	"github.com/wistia/wistia-cli/internal/output"
	"github.com/wistia/wistia-cli/internal/sdk"
	"github.com/wistia/wistia-cli/internal/sdk/models/operations"
	"github.com/wistia/wistia-cli/internal/usage"
)

var applyCmdMeta = []flagutil.FlagMeta{
	{FlagName: "brand-id", Shorthand: "b", FieldPath: "BrandID", Kind: flagutil.FlagKindString, Required: true, Description: "The id of the brand to apply [required]"},
	{FlagName: "resource-type", FieldPath: "Body.ResourceType", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"media", "folder", "channel"}, Description: "The kind of resource being branded. Webinars can't be branded through this endpoint yet. (options: media, folder, channel) [required]"},
	{FlagName: "resource-id", FieldPath: "Body.ResourceID", Kind: flagutil.FlagKindString, Required: true, Description: "The id of the resource being branded. [required]"},
	{FlagName: "clear-overrides", Shorthand: "c", FieldPath: "Body.ClearOverrides", Kind: flagutil.FlagKindBool, Optional: true, HasDefault: true, DefaultBool: true, Description: "When true (the default), appearance settings the resource had set directly are cleared for the fields the brand controls, so the brand is what shows. Set to false to leave them in place, in which case they continue to win over the brand."},
}

// initApplyCmd initializes the apply command.
func initApplyCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "apply",
		Short:   "Apply Brand",
		Long:    "Applies a brand to a media, folder, or channel, so that resource is styled\nby the brand's colors, fonts, logos, and layout.\n\nA brand has no effect until it is applied to something. Media inherit from\ntheir folder, and folders from the account's default brand, so applying a\nbrand to a folder styles everything inside it that has no brand of its own.\n\nApplying the account-level default brand (`is_default: true`) is how a\nresource is un-branded: it detaches the resource so it inherits again.\n\nBy default this also clears any brand-mapped appearance settings the\nresource had set directly, so the brand is what shows. Pass\n`clear_overrides: false` to leave those in place.\n\nResponds with the brand now in effect on the resource, which is not always\nthe one you applied — detaching a media returns the brand it falls back to.\n\nWebinars can't be branded through this endpoint yet.\n\n## Requires api token with one of the following permissions\n```\nAll data\n```\n\nTokens with the \"Act with a team member's permissions\" permission\n(`all:delegate_to_contact_permissions` scope) can also be used. Requests\nmade with such a token are authorized using the permissions of the\ncontact assigned to the token.",
		Example: "  wistia brands apply --brand-id <id> --resource-type media --resource-id abcde12345",
		RunE:    runApplyCmd,
	}
	flagutil.RegisterFlags(cmd, applyCmdMeta)
	if err := flagutil.ValidateMeta[operations.PostBrandsBrandIDApplyRequest](applyCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for apply: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runApplyCmd executes the apply command.
func runApplyCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, applyCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, applyCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PostBrandsBrandIDApplyRequest](cmd, applyCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Brands.Apply(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
