// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: edfdf1df8a7d

package contacts

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/wistia/wistia-cli/internal/client"
	"github.com/wistia/wistia-cli/internal/flagutil"
	"github.com/wistia/wistia-cli/internal/output"
	"github.com/wistia/wistia-cli/internal/sdk"
	"github.com/wistia/wistia-cli/internal/sdk/models/operations"
	"github.com/wistia/wistia-cli/internal/usage"
)

var createCmdMeta = []flagutil.FlagMeta{
	{FlagName: "contacts", Shorthand: "c", FieldPath: "Contacts", Kind: flagutil.FlagKindString, Required: true, Description: "A comma-, whitespace-, or newline-separated list of email addresses to\ninvite to the account. Each entry becomes a new contact if one does not\nalready exist for that email.\n[required]"},
}

// initCreateCmd initializes the create command.
func initCreateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create",
		Short:   "Invite Contacts",
		Long:    "Invites one or more people to the account by email. Accepts a\ncomma/whitespace/newline-separated list; each entry becomes a new contact\nif one does not already exist for that email.\n\nAn [expiring access token](https://docs.wistia.com/reference/post_expiring-token)\ncreated with the `all:delegate_to_contact_permissions` scope and an\n`account` authorization granting the `manage-team` permission can also be\nused.\n\n## Requires api token with one of the following permissions\n```\nRead, update & delete anything\n```",
		Example: "  wistia contacts create --contacts 'alice@example.com, bob@example.com'",
		Args:    cobra.NoArgs,
		RunE:    runCreateCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "post_/contacts",
		},
	}
	flagutil.RegisterFlags(cmd, createCmdMeta)
	if err := flagutil.ValidateMeta[operations.PostContactsRequest](createCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin; @path reads a file, @- reads stdin to EOF.")
	_ = flagutil.AnnotatePromptFlag(cmd, "body", flagutil.PromptFlagSpec{Required: false, Kind: "json", BodyFlag: true})
	cmd.Annotations[flagutil.AnnotationWholeBodyFlag] = "body"
	if err := flagutil.AnnotateBodyFields(cmd, createCmdMeta, "", "body"); err != nil {
		return fmt.Errorf("annotate body fields for create: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runCreateCmd executes the create command.
func runCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	request, err := flagutil.BuildRequest[operations.PostContactsRequest](cmd, createCmdMeta, "", "body")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	stopProgress := output.StartRequestProgress(cmd)
	defer stopProgress()
	res, err := s.Contacts.Create(cmd.Context(), *request, sdkOpts...)
	stopProgress()
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
