workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Wistia-OAS:
        inputs:
            - location: https://wistia.github.io/wistia/api/openapi-upload.yaml
            - location: https://wistia.github.io/wistia/api/openapi-modern.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/wistia/wistia/wistia-oas
targets:
    wistia:
        target: cli
        source: Wistia-OAS
