// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 98b2c1d2d26e

package localizations

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/wistia/wistia-cli/internal/client"
	"github.com/wistia/wistia-cli/internal/flagutil"
	"github.com/wistia/wistia-cli/internal/output"
	"github.com/wistia/wistia-cli/internal/sdk"
	"github.com/wistia/wistia-cli/internal/sdk/models/operations"
	"github.com/wistia/wistia-cli/internal/usage"
)

var deleteCmdMeta = []flagutil.FlagMeta{
	{FlagName: "media-hashed-id", Shorthand: "m", FieldPath: "MediaHashedID", Kind: flagutil.FlagKindString, Required: true, Description: "The hashed ID of the localization's media. [required]"},
	{FlagName: "localization-hashed-id", Shorthand: "l", FieldPath: "LocalizationHashedID", Kind: flagutil.FlagKindString, Required: true, Description: "The hashed ID of the localization to delete. [required]"},
}

// initDeleteCmd initializes the delete command.
func initDeleteCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "delete",
		Short:   "Delete Localization",
		Long:    "Deletes a localization.\n\n## Requires api token with one of the following permissions\n```\nRead, update & delete anything\n```\n\nTokens with the \"Act with a team member's permissions\" permission\n(`all:delegate_to_contact_permissions` scope) can also be used. Requests\nmade with such a token are authorized using the permissions of the\ncontact assigned to the token.\n\nAn [expiring access token](https://docs.wistia.com/reference/post_expiring-token)\ncreated with the `all:delegate_to_contact_permissions` scope and an\nauthorization granting both the `update` and the `edit-transcripts`\npermissions on the source media can also be used: `edit-transcripts` finds\nthe localization and `update` allows deleting it.",
		Example: "  wistia localizations delete --media-hashed-id <id> --localization-hashed-id <id>",
		Args:    cobra.NoArgs,
		RunE:    runDeleteCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "delete_/medias/{mediaHashedId}/localizations/{localizationHashedId}",
		},
	}
	flagutil.RegisterFlags(cmd, deleteCmdMeta)
	if err := flagutil.ValidateMeta[operations.DeleteMediasMediaHashedIDLocalizationsLocalizationHashedIDRequest](deleteCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for delete: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runDeleteCmd executes the delete command.
func runDeleteCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	req, err := flagutil.BuildRequest[operations.DeleteMediasMediaHashedIDLocalizationsLocalizationHashedIDRequest](cmd, deleteCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	stopProgress := output.StartRequestProgress(cmd)
	defer stopProgress()
	res, err := s.Localizations.Delete(cmd.Context(), *req, sdkOpts...)
	stopProgress()
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
