// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a7a7ff6bbdac

package sharelinks

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/wistia/wistia-cli/internal/client"
	"github.com/wistia/wistia-cli/internal/flagutil"
	"github.com/wistia/wistia-cli/internal/interactive"
	"github.com/wistia/wistia-cli/internal/output"
	"github.com/wistia/wistia-cli/internal/sdk"
	"github.com/wistia/wistia-cli/internal/sdk/models/operations"
	"github.com/wistia/wistia-cli/internal/usage"
)

var getCmdMeta = []flagutil.FlagMeta{
	{FlagName: "media-id", Shorthand: "m", FieldPath: "MediaID", Kind: flagutil.FlagKindString, Required: true, Description: "The hashed ID of the media. [required]"},
}

// initGetCmd initializes the get command.
func initGetCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get",
		Short:   "Show share link",
		Long:    "Fetches the share link for a single media. If the media does not have a\nshare link yet, one is created on first request with a default\nvisibility derived from the parent folder.\n\n## Requires api token with one of the following permissions\n```\nRead all folder and media data\n```",
		Example: "  wistia share-links get --media-id <id>",
		RunE:    runGetCmd,
	}
	flagutil.RegisterFlags(cmd, getCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetMediasMediaIDShareLinkRequest](getCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetCmd executes the get command.
func runGetCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetMediasMediaIDShareLinkRequest](cmd, getCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.ShareLinks.Get(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
