// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9eae124ade6d

package sharelinks

import (
	"github.com/spf13/cobra"
	"github.com/wistia/wistia-cli/internal/usage"
)

func InitShareLinksRoot(parent *cobra.Command) error {
	var ShareLinksCmd = &cobra.Command{
		Use:   "share-links",
		Short: "Operations for share-links",
		Long:  "Operations for share-links",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
		Aliases: []string{"sl"},
	}

	if err := initGetCmd(ShareLinksCmd); err != nil {
		return err
	}

	if err := initUpdateCmd(ShareLinksCmd); err != nil {
		return err
	}

	if err := initDeleteCmd(ShareLinksCmd); err != nil {
		return err
	}

	parent.AddCommand(ShareLinksCmd)
	return nil
}
