// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d9dd62bc9c81

package analyticsmedia

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/wistia/wistia-cli/internal/client"
	"github.com/wistia/wistia-cli/internal/flagutil"
	"github.com/wistia/wistia-cli/internal/interactive"
	"github.com/wistia/wistia-cli/internal/output"
	"github.com/wistia/wistia-cli/internal/sdk"
	"github.com/wistia/wistia-cli/internal/sdk/models/operations"
	"github.com/wistia/wistia-cli/internal/usage"
)

var getTrafficCmdMeta = []flagutil.FlagMeta{
	{FlagName: "media-id", Shorthand: "m", FieldPath: "MediaID", Kind: flagutil.FlagKindString, Required: true, Description: "The hashed ID of the video. [required]"},
	{FlagName: "start-date", FieldPath: "StartDate", Kind: flagutil.FlagKindDate, Required: true, Description: "Start date for the analytics period in ISO 8601 format (YYYY-MM-DD). Inclusive — the range starts at the beginning of this date. [required]"},
	{FlagName: "end-date", Shorthand: "e", FieldPath: "EndDate", Kind: flagutil.FlagKindDate, Required: true, Description: "End date for the analytics period in ISO 8601 format (YYYY-MM-DD). Exclusive — the range ends before the beginning of this date. [required]"},
	{FlagName: "group-by", Shorthand: "g", FieldPath: "GroupBy", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"utm_campaign", "utm_source", "utm_medium", "referrer_domain", "viewer_screen_size"}, Description: "The dimension to group traffic data by. (options: utm_campaign, utm_source, utm_medium, referrer_domain, viewer_screen_size) [required]"},
	{FlagName: "sort-by", FieldPath: "SortBy", Kind: flagutil.FlagKindEnum, Optional: true, HasDefault: true, DefaultStr: "plays", EnumValues: []string{"plays", "loads", "engagement_rate"}, Description: "The metric to sort results by. (options: plays, loads, engagement_rate)"},
	{FlagName: "sort-direction", FieldPath: "SortDirection", Kind: flagutil.FlagKindEnum, Optional: true, HasDefault: true, DefaultStr: "desc", EnumValues: []string{"asc", "desc"}, Description: "The sort direction. (options: asc, desc)"},
	{FlagName: "per-page", Shorthand: "p", FieldPath: "PerPage", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 100, Description: "Number of results to return (max 100)."},
}

// initGetTrafficCmd initializes the get-traffic command.
func initGetTrafficCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-traffic",
		Short:   "Show Media Traffic Breakdown",
		Long:    "Retrieve traffic breakdown analytics for a video, grouped by a specified dimension\nsuch as UTM campaign, UTM source, UTM medium, referrer domain, or viewer screen size.\n\nThe date range between `start_date` and `end_date` must not exceed 2 years.\n\n<!--- HIDE-MCP -->\n## Requires api token with one of the following permissions\n```\nRead detailed stats\n```\n<!--- /HIDE-MCP -->",
		Example: "  wistia analytics-media get-traffic --media-id <id> --start-date 2026-11-05 --end-date 2026-08-31 --group-by utm_source",
		RunE:    runGetTrafficCmd,
		Aliases: []string{"gtr"},
	}
	flagutil.RegisterFlags(cmd, getTrafficCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetAnalyticsMediasMediaIDTrafficRequest](getTrafficCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-traffic: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetTrafficCmd executes the get-traffic command.
func runGetTrafficCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getTrafficCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getTrafficCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetAnalyticsMediasMediaIDTrafficRequest](cmd, getTrafficCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.AnalyticsMedia.GetTraffic(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
