// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 439c4a4d6b84

package analyticsmedia

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/wistia/wistia-cli/internal/client"
	"github.com/wistia/wistia-cli/internal/flagutil"
	"github.com/wistia/wistia-cli/internal/interactive"
	"github.com/wistia/wistia-cli/internal/output"
	"github.com/wistia/wistia-cli/internal/sdk"
	"github.com/wistia/wistia-cli/internal/sdk/models/operations"
	"github.com/wistia/wistia-cli/internal/usage"
)

var getTimeseriesCmdMeta = []flagutil.FlagMeta{
	{FlagName: "media-id", Shorthand: "m", FieldPath: "MediaID", Kind: flagutil.FlagKindString, Required: true, Description: "The hashed ID of the video. [required]"},
	{FlagName: "start-date", Shorthand: "s", FieldPath: "StartDate", Kind: flagutil.FlagKindDate, Required: true, Description: "Start date for the analytics period in ISO 8601 format (YYYY-MM-DD). Inclusive — the range starts at the beginning of this date. [required]"},
	{FlagName: "end-date", Shorthand: "e", FieldPath: "EndDate", Kind: flagutil.FlagKindDate, Required: true, Description: "End date for the analytics period in ISO 8601 format (YYYY-MM-DD). Exclusive — the range ends before the beginning of this date. [required]"},
	{FlagName: "granularity", Shorthand: "g", FieldPath: "Granularity", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"daily", "weekly", "monthly"}, Description: "The time granularity for the timeseries data. (options: daily, weekly, monthly) [required]"},
}

// initGetTimeseriesCmd initializes the get-timeseries command.
func initGetTimeseriesCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-timeseries [media-id]",
		Short:   "Show Media Analytics Timeseries",
		Long:    "Retrieve analytics timeseries data for a video over a date range with configurable\ngranularity. Returns an array of timestamped metric buckets.\n\nThe date range between `start_date` and `end_date` must not exceed 2 years.\n\n\n## Requires api token with one of the following permissions\n```\nRead detailed stats\n```\n\nTokens with the \"Act with a team member's permissions\" permission\n(`all:delegate_to_contact_permissions` scope) can also be used. Requests\nmade with such a token are authorized using the permissions of the\ncontact assigned to the token.\n\nAn [expiring access token](https://docs.wistia.com/reference/post_expiring-token)\ncreated with the `all:delegate_to_contact_permissions` scope and an\nauthorization granting the `view-stats` permission on this media can also\nbe used.",
		Example: "  wistia analytics-media get-timeseries --media-id <id> --start-date 2024-05-04 --end-date 2025-12-15 --granularity daily",
		Args:    flagutil.PositionalFlagArgs,
		RunE:    runGetTimeseriesCmd,
		Aliases: []string{"gt"},
		Annotations: map[string]string{
			"speakeasy_operation": "get_/analytics/medias/{mediaId}/timeseries",
		},
	}
	flagutil.RegisterFlags(cmd, getTimeseriesCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetAnalyticsMediasMediaIDTimeseriesRequest](getTimeseriesCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-timeseries: %w", err)
	}
	if err := flagutil.DeclarePositionalFlag(cmd, "media-id", "The hashed ID of the video. (or pass it as the [media-id] argument)", true); err != nil {
		return err
	}
	if err := interactive.Declare(cmd, interactive.CommandSpec{Args: []interactive.ArgSpec{
		{Name: "media-id", Summary: "The hashed ID of the video.", Required: true, SatisfiedBy: []string{"media-id"}},
	}}); err != nil {
		return fmt.Errorf("declare interactive arguments for get-timeseries: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetTimeseriesCmd executes the get-timeseries command.
func runGetTimeseriesCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if err := flagutil.ResolvePositionalFlag(cmd, args); err != nil {
		return err
	}
	req, err := flagutil.BuildRequest[operations.GetAnalyticsMediasMediaIDTimeseriesRequest](cmd, getTimeseriesCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	stopProgress := output.StartRequestProgress(cmd)
	defer stopProgress()
	res, err := s.AnalyticsMedia.GetTimeseries(cmd.Context(), *req, sdkOpts...)
	stopProgress()
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
