// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b4d86c2aec47

package media

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/wistia/wistia-cli/internal/client"
	"github.com/wistia/wistia-cli/internal/flagutil"
	"github.com/wistia/wistia-cli/internal/interactive"
	"github.com/wistia/wistia-cli/internal/output"
	"github.com/wistia/wistia-cli/internal/sdk"
	"github.com/wistia/wistia-cli/internal/sdk/models/operations"
	"github.com/wistia/wistia-cli/internal/usage"
)

var getStatsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "media-hashed-id", Shorthand: "m", FieldPath: "MediaHashedID", Kind: flagutil.FlagKindString, Required: true, Description: "The hashed ID of the video. [required]"},
}

// initGetStatsCmd initializes the get-stats command.
func initGetStatsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-stats [media-hashed-id]",
		Short:   "Show Media Aggregated Stats",
		Long:    "Aggregated tracking statistics for a video embedded on your site.\n\n## Requires api token with one of the following permissions\n```\nRead all folder and media data\n```\n\nTokens with the \"Act with a team member's permissions\" permission\n(`all:delegate_to_contact_permissions` scope) can also be used. Requests\nmade with such a token are authorized using the permissions of the\ncontact assigned to the token.\n\nAn [expiring access token](https://docs.wistia.com/reference/post_expiring-token)\ncreated with the `all:delegate_to_contact_permissions` scope and an\nauthorization granting the `view-stats` permission on this media can also\nbe used.",
		Example: "  wistia media get-stats --media-hashed-id <id>",
		Args:    flagutil.PositionalFlagArgs,
		RunE:    runGetStatsCmd,
		Aliases: []string{"gs"},
		Annotations: map[string]string{
			"speakeasy_operation": "get_/medias/{mediaHashedId}/stats",
		},
	}
	flagutil.RegisterFlags(cmd, getStatsCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetMediasMediaHashedIDStatsRequest](getStatsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-stats: %w", err)
	}
	if err := flagutil.DeclarePositionalFlag(cmd, "media-hashed-id", "The hashed ID of the video. (or pass it as the [media-hashed-id] argument)", true); err != nil {
		return err
	}
	if err := interactive.Declare(cmd, interactive.CommandSpec{Args: []interactive.ArgSpec{
		{Name: "media-hashed-id", Summary: "The hashed ID of the video.", Required: true, SatisfiedBy: []string{"media-hashed-id"}},
	}}); err != nil {
		return fmt.Errorf("declare interactive arguments for get-stats: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetStatsCmd executes the get-stats command.
func runGetStatsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if err := flagutil.ResolvePositionalFlag(cmd, args); err != nil {
		return err
	}
	req, err := flagutil.BuildRequest[operations.GetMediasMediaHashedIDStatsRequest](cmd, getStatsCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Media.GetStats(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
