// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package media

import (
	"github.com/spf13/cobra"
	"github.com/wistia/wistia-cli/internal/usage"
)

func InitMediaRoot(parent *cobra.Command) error {
	var MediaCmd = &cobra.Command{
		Use:   "media",
		Short: "Operations for media",
		Long:  "Operations for media",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initUploadFormCmd(MediaCmd); err != nil {
		return err
	}

	if err := initUploadMultipartCmd(MediaCmd); err != nil {
		return err
	}

	if err := initListCmd(MediaCmd); err != nil {
		return err
	}

	if err := initGetCmd(MediaCmd); err != nil {
		return err
	}

	if err := initUpdateCmd(MediaCmd); err != nil {
		return err
	}

	if err := initDeleteCmd(MediaCmd); err != nil {
		return err
	}

	if err := initCopyCmd(MediaCmd); err != nil {
		return err
	}

	if err := initSwapCmd(MediaCmd); err != nil {
		return err
	}

	if err := initGetStatsCmd(MediaCmd); err != nil {
		return err
	}

	if err := initTranslateCmd(MediaCmd); err != nil {
		return err
	}

	if err := initArchiveCmd(MediaCmd); err != nil {
		return err
	}

	if err := initMoveCmd(MediaCmd); err != nil {
		return err
	}

	if err := initRestoreCmd(MediaCmd); err != nil {
		return err
	}

	parent.AddCommand(MediaCmd)
	return nil
}
