// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 03f675e30f70

package media

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/wistia/wistia-cli/internal/client"
	"github.com/wistia/wistia-cli/internal/flagutil"
	"github.com/wistia/wistia-cli/internal/interactive"
	"github.com/wistia/wistia-cli/internal/output"
	"github.com/wistia/wistia-cli/internal/sdk"
	"github.com/wistia/wistia-cli/internal/sdk/models/operations"
	"github.com/wistia/wistia-cli/internal/usage"
)

var translateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "media-hashed-id", Shorthand: "m", FieldPath: "MediaHashedID", Kind: flagutil.FlagKindString, Required: true, Description: "The hashed ID of the media. [required]"},
	{FlagName: "target-language", Shorthand: "t", FieldPath: "Body.TargetLanguage", Kind: flagutil.FlagKindString, Required: true, Description: "The language to translate the transcript to as a 3-character IETF language code. [required]"},
	{FlagName: "source-language", Shorthand: "s", FieldPath: "Body.SourceLanguage", Kind: flagutil.FlagKindString, Optional: true, Description: "The language of the source transcript to be translated as a 3-character IETF language code. If not provided, the media's default transcript language will be used."},
}

// initTranslateCmd initializes the translate command.
func initTranslateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "translate",
		Short:   "Translate Media",
		Long:    "Translates the transcript for a media.\n\n## Requires api token with one of the following permissions\n```\nRead, update & delete anything\n```",
		Example: "  wistia media translate --media-hashed-id <id> --target-language <value>",
		RunE:    runTranslateCmd,
	}
	flagutil.RegisterFlags(cmd, translateCmdMeta)
	if err := flagutil.ValidateMeta[operations.PostMediasMediaHashedIDTranslateRequest](translateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for translate: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runTranslateCmd executes the translate command.
func runTranslateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, translateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, translateCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.PostMediasMediaHashedIDTranslateRequest](cmd, translateCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Media.Translate(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
