// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b1c2d097202c

package webinarcollaborators

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/wistia/wistia-cli/internal/client"
	"github.com/wistia/wistia-cli/internal/flagutil"
	"github.com/wistia/wistia-cli/internal/output"
	"github.com/wistia/wistia-cli/internal/sdk"
	"github.com/wistia/wistia-cli/internal/sdk/models/operations"
	"github.com/wistia/wistia-cli/internal/usage"
)

var deleteCmdMeta = []flagutil.FlagMeta{
	{FlagName: "webinar-id", Shorthand: "w", FieldPath: "WebinarID", Kind: flagutil.FlagKindString, Required: true, Description: "Webinar Hashed ID [required]"},
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindInt64, Required: true, Description: "Collaborator ID [required]"},
}

// initDeleteCmd initializes the delete command.
func initDeleteCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "delete",
		Short:   "Delete Webinar Collaborator",
		Long:    "Removes a collaborator's producer access to a webinar.\n\n## Requires api token with one of the following permissions\n```\nRead, update & delete anything\n```\n\nTokens with the \"Act with a team member's permissions\" permission\n(`all:delegate_to_contact_permissions` scope) can also be used. Requests\nmade with such a token are authorized using the permissions of the\ncontact assigned to the token.\n\nAn [expiring access token](https://docs.wistia.com/reference/post_expiring-token)\ncreated with the `all:delegate_to_contact_permissions` scope and an\nauthorization granting the `update` permission on this webinar can also\nbe used.",
		Example: "  wistia webinar-collaborators delete --webinar-id <id> --id 428246",
		Args:    cobra.NoArgs,
		RunE:    runDeleteCmd,
		Annotations: map[string]string{
			"speakeasy_operation": "delete_/webinars/{webinarId}/collaborators/{id}",
		},
	}
	flagutil.RegisterFlags(cmd, deleteCmdMeta)
	if err := flagutil.ValidateMeta[operations.DeleteWebinarsWebinarIDCollaboratorsIDRequest](deleteCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for delete: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runDeleteCmd executes the delete command.
func runDeleteCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	req, err := flagutil.BuildRequest[operations.DeleteWebinarsWebinarIDCollaboratorsIDRequest](cmd, deleteCmdMeta, "", "")
	if err != nil {
		return flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.WebinarCollaborators.Delete(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
